from django.urls import path

from projetos.views.gestao_empresa import (
    gestao_clientes_contratos,
    gestao_compliance_seguranca,
    gestao_compliance_dashboard_export_csv,
    gestao_compras_fornecedores,
    gestao_compras_export_csv,
    gestao_compras_export_xlsx,
    gestao_hub,
    gestao_checklist_hse_create,
    gestao_checklist_hse_delete,
    gestao_checklist_hse_evidencia_create,
    gestao_checklist_hse_update,
    gestao_auditoria_hse_create,
    gestao_auditoria_hse_delete,
    gestao_auditoria_hse_evidencia_create,
    gestao_auditoria_hse_update,
    gestao_plano_auditoria_hse_create,
    gestao_plano_auditoria_hse_delete,
    gestao_plano_auditoria_hse_gerar,
    gestao_plano_auditoria_hse_update,
    gestao_acao_preventiva_create,
    gestao_acao_preventiva_delete,
    gestao_acao_preventiva_evidencia_create,
    gestao_acao_preventiva_estado,
    gestao_acao_preventiva_update,
    gestao_acao_corretiva_create,
    gestao_acao_corretiva_delete,
    gestao_acao_corretiva_evidencia_create,
    gestao_acao_corretiva_fecho,
    gestao_acao_corretiva_estado,
    gestao_acao_corretiva_update,
    gestao_evidencia_compliance_delete,
    gestao_incidente_create,
    gestao_incidente_delete,
    gestao_incidente_evidencia_create,
    gestao_incidente_estado,
    gestao_incidente_update,
    gestao_notificacao_create,
    gestao_notificacao_delete,
    gestao_notificacao_estado,
    gestao_notificacao_update,
    gestao_notificacoes_export_csv,
    gestao_notificacoes,
    gestao_planeamento,
    gestao_fornecedor_create,
    gestao_fornecedor_update,
    gestao_fornecedor_delete,
    gestao_pedido_compra_create,
    gestao_pedido_compra_delete,
    gestao_pedido_compra_estado,
    gestao_pedido_compra_comparar,
    gestao_pedido_compra_selecionar_melhor,
    gestao_pedido_compra_selecionar_proposta,
    gestao_pedido_compra_update,
    gestao_proposta_compra_create,
    gestao_proposta_compra_update,
    gestao_proposta_compra_delete,
    gestao_relatorios_export_csv,
    gestao_relatorios_export_pdf,
    gestao_relatorios_export_xlsx,
    gestao_relatorios_enviar_email,
    gestao_relatorios_executivos,
    gestao_relatorios_agendamento,
    gestao_relatorios_agendamento_executar_agora,
    gestao_rh_assiduidade,
)

urlpatterns = [
    path("", gestao_hub, name="gestao_hub"),
    path("clientes-contratos/", gestao_clientes_contratos, name="gestao_clientes_contratos"),
    path("planeamento/", gestao_planeamento, name="gestao_planeamento"),
    path("rh-assiduidade/", gestao_rh_assiduidade, name="gestao_rh_assiduidade"),
    path("compras-fornecedores/", gestao_compras_fornecedores, name="gestao_compras_fornecedores"),
    path("compras-fornecedores/export/csv/", gestao_compras_export_csv, name="gestao_compras_export_csv"),
    path("compras-fornecedores/export/xlsx/", gestao_compras_export_xlsx, name="gestao_compras_export_xlsx"),
    path("compras-fornecedores/fornecedores/novo/", gestao_fornecedor_create, name="gestao_fornecedor_create"),
    path("compras-fornecedores/fornecedores/<uuid:pk>/editar/", gestao_fornecedor_update, name="gestao_fornecedor_update"),
    path("compras-fornecedores/fornecedores/<uuid:pk>/apagar/", gestao_fornecedor_delete, name="gestao_fornecedor_delete"),
    path("compras-fornecedores/pedidos/novo/", gestao_pedido_compra_create, name="gestao_pedido_compra_create"),
    path("compras-fornecedores/pedidos/<uuid:pk>/editar/", gestao_pedido_compra_update, name="gestao_pedido_compra_update"),
    path("compras-fornecedores/pedidos/<uuid:pk>/apagar/", gestao_pedido_compra_delete, name="gestao_pedido_compra_delete"),
    path("compras-fornecedores/pedidos/<uuid:pk>/comparar/", gestao_pedido_compra_comparar, name="gestao_pedido_compra_comparar"),
    path(
        "compras-fornecedores/pedidos/<uuid:pk>/selecionar-melhor/",
        gestao_pedido_compra_selecionar_melhor,
        name="gestao_pedido_compra_selecionar_melhor",
    ),
    path(
        "compras-fornecedores/pedidos/<uuid:pedido_pk>/propostas/<uuid:proposta_pk>/selecionar/",
        gestao_pedido_compra_selecionar_proposta,
        name="gestao_pedido_compra_selecionar_proposta",
    ),
    path(
        "compras-fornecedores/pedidos/<uuid:pedido_pk>/propostas/nova/",
        gestao_proposta_compra_create,
        name="gestao_proposta_compra_create",
    ),
    path("compras-fornecedores/propostas/<uuid:pk>/editar/", gestao_proposta_compra_update, name="gestao_proposta_compra_update"),
    path("compras-fornecedores/propostas/<uuid:pk>/apagar/", gestao_proposta_compra_delete, name="gestao_proposta_compra_delete"),
    path("compras-fornecedores/pedidos/<uuid:pk>/<str:estado>/", gestao_pedido_compra_estado, name="gestao_pedido_compra_estado"),
    path("compliance-seguranca/", gestao_compliance_seguranca, name="gestao_compliance_seguranca"),
    path(
        "compliance-seguranca/export/dashboard-csv/",
        gestao_compliance_dashboard_export_csv,
        name="gestao_compliance_dashboard_export_csv",
    ),
    path("compliance-seguranca/checklists/nova/", gestao_checklist_hse_create, name="gestao_checklist_hse_create"),
    path("compliance-seguranca/checklists/<uuid:pk>/editar/", gestao_checklist_hse_update, name="gestao_checklist_hse_update"),
    path("compliance-seguranca/checklists/<uuid:pk>/apagar/", gestao_checklist_hse_delete, name="gestao_checklist_hse_delete"),
    path("compliance-seguranca/checklists/<uuid:pk>/evidencias/nova/", gestao_checklist_hse_evidencia_create, name="gestao_checklist_hse_evidencia_create"),
    path("compliance-seguranca/auditorias/nova/", gestao_auditoria_hse_create, name="gestao_auditoria_hse_create"),
    path("compliance-seguranca/auditorias/<uuid:pk>/editar/", gestao_auditoria_hse_update, name="gestao_auditoria_hse_update"),
    path("compliance-seguranca/auditorias/<uuid:pk>/apagar/", gestao_auditoria_hse_delete, name="gestao_auditoria_hse_delete"),
    path("compliance-seguranca/auditorias/<uuid:pk>/evidencias/nova/", gestao_auditoria_hse_evidencia_create, name="gestao_auditoria_hse_evidencia_create"),
    path("compliance-seguranca/planos-auditoria/novo/", gestao_plano_auditoria_hse_create, name="gestao_plano_auditoria_hse_create"),
    path("compliance-seguranca/planos-auditoria/<uuid:pk>/editar/", gestao_plano_auditoria_hse_update, name="gestao_plano_auditoria_hse_update"),
    path("compliance-seguranca/planos-auditoria/<uuid:pk>/apagar/", gestao_plano_auditoria_hse_delete, name="gestao_plano_auditoria_hse_delete"),
    path("compliance-seguranca/planos-auditoria/gerar/", gestao_plano_auditoria_hse_gerar, name="gestao_plano_auditoria_hse_gerar"),
    path("compliance-seguranca/acoes-corretivas/nova/", gestao_acao_corretiva_create, name="gestao_acao_corretiva_create"),
    path("compliance-seguranca/acoes-corretivas/<uuid:pk>/editar/", gestao_acao_corretiva_update, name="gestao_acao_corretiva_update"),
    path("compliance-seguranca/acoes-corretivas/<uuid:pk>/apagar/", gestao_acao_corretiva_delete, name="gestao_acao_corretiva_delete"),
    path("compliance-seguranca/acoes-corretivas/<uuid:pk>/evidencias/nova/", gestao_acao_corretiva_evidencia_create, name="gestao_acao_corretiva_evidencia_create"),
    path("compliance-seguranca/acoes-corretivas/<uuid:pk>/fecho/", gestao_acao_corretiva_fecho, name="gestao_acao_corretiva_fecho"),
    path("compliance-seguranca/acoes-corretivas/<uuid:pk>/<str:estado>/", gestao_acao_corretiva_estado, name="gestao_acao_corretiva_estado"),
    path("compliance-seguranca/acoes-preventivas/nova/", gestao_acao_preventiva_create, name="gestao_acao_preventiva_create"),
    path("compliance-seguranca/acoes-preventivas/<uuid:pk>/editar/", gestao_acao_preventiva_update, name="gestao_acao_preventiva_update"),
    path("compliance-seguranca/acoes-preventivas/<uuid:pk>/apagar/", gestao_acao_preventiva_delete, name="gestao_acao_preventiva_delete"),
    path("compliance-seguranca/acoes-preventivas/<uuid:pk>/evidencias/nova/", gestao_acao_preventiva_evidencia_create, name="gestao_acao_preventiva_evidencia_create"),
    path("compliance-seguranca/acoes-preventivas/<uuid:pk>/<str:estado>/", gestao_acao_preventiva_estado, name="gestao_acao_preventiva_estado"),
    path("compliance-seguranca/incidentes/novo/", gestao_incidente_create, name="gestao_incidente_create"),
    path("compliance-seguranca/incidentes/<uuid:pk>/editar/", gestao_incidente_update, name="gestao_incidente_update"),
    path("compliance-seguranca/incidentes/<uuid:pk>/apagar/", gestao_incidente_delete, name="gestao_incidente_delete"),
    path("compliance-seguranca/incidentes/<uuid:pk>/evidencias/nova/", gestao_incidente_evidencia_create, name="gestao_incidente_evidencia_create"),
    path("compliance-seguranca/incidentes/<uuid:pk>/<str:estado>/", gestao_incidente_estado, name="gestao_incidente_estado"),
    path("compliance-seguranca/evidencias/<uuid:pk>/apagar/", gestao_evidencia_compliance_delete, name="gestao_evidencia_compliance_delete"),
    path("notificacoes/", gestao_notificacoes, name="gestao_notificacoes"),
    path("notificacoes/nova/", gestao_notificacao_create, name="gestao_notificacao_create"),
    path("notificacoes/<uuid:pk>/editar/", gestao_notificacao_update, name="gestao_notificacao_update"),
    path("notificacoes/<uuid:pk>/apagar/", gestao_notificacao_delete, name="gestao_notificacao_delete"),
    path("notificacoes/<uuid:pk>/<str:estado>/", gestao_notificacao_estado, name="gestao_notificacao_estado"),
    path("notificacoes/export/csv/", gestao_notificacoes_export_csv, name="gestao_notificacoes_export_csv"),
    path("relatorios-executivos/", gestao_relatorios_executivos, name="gestao_relatorios_executivos"),
    path("relatorios-executivos/export/csv/", gestao_relatorios_export_csv, name="gestao_relatorios_export_csv"),
    path("relatorios-executivos/export/pdf/", gestao_relatorios_export_pdf, name="gestao_relatorios_export_pdf"),
    path("relatorios-executivos/export/xlsx/", gestao_relatorios_export_xlsx, name="gestao_relatorios_export_xlsx"),
    path("relatorios-executivos/enviar-email/", gestao_relatorios_enviar_email, name="gestao_relatorios_enviar_email"),
    path("relatorios-executivos/agendamento/", gestao_relatorios_agendamento, name="gestao_relatorios_agendamento"),
    path(
        "relatorios-executivos/agendamento/executar-agora/",
        gestao_relatorios_agendamento_executar_agora,
        name="gestao_relatorios_agendamento_executar_agora",
    ),
]
