from projetos.forms.projeto import *
from projetos.forms.furo import *
from projetos.forms.empregado import *
from projetos.forms.maquina import *
from projetos.forms.material import *
from projetos.forms.medicao import *
from projetos.forms.registo import *
from projetos.forms.configuracao_perfuracao import *
from projetos.forms.empregado_furo import *
from projetos.forms.empregado_area import *