# Generated by Django 6.0.4 on 2026-04-21 17:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0009_alter_movimentofinanceiroplataforma_categoria_and_more'),
        ('projetos', '0009_remove_individual_nib'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogGeologicoFuro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('data_registo', models.DateField(default=django.utils.timezone.now)),
                ('intervalo_de', models.FloatField()),
                ('intervalo_ate', models.FloatField()),
                ('recuperacao_testemunho_percent', models.FloatField(blank=True, null=True)),
                ('rqd_percent', models.FloatField(blank=True, null=True)),
                ('litologia_principal', models.CharField(max_length=120)),
                ('litologia_secundaria', models.CharField(blank=True, max_length=120)),
                ('cor', models.CharField(blank=True, max_length=80)),
                ('granulometria', models.CharField(blank=True, max_length=80)),
                ('alteracao', models.CharField(blank=True, max_length=120)),
                ('mineralizacao', models.CharField(blank=True, max_length=120)),
                ('estrutura', models.CharField(blank=True, max_length=120)),
                ('densidade_fraturas', models.CharField(blank=True, max_length=120)),
                ('nivel_agua_m', models.FloatField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('imagem_referencia', models.ImageField(blank=True, null=True, upload_to='geologia/logging/imagens/')),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_geologicos_furo', to='plataforma.empresa')),
                ('furo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_geologicos', to='projetos.furo')),
                ('medicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_geologicos', to='projetos.medicao')),
            ],
            options={
                'verbose_name': 'Log Geologico do Furo',
                'verbose_name_plural': 'Logs Geologicos do Furo',
                'ordering': ['intervalo_de', 'intervalo_ate', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoLogGeologico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('documento', 'Documento'), ('ortomosaico', 'Ortomosaico'), ('modelo_3d', 'Modelo 3D')], default='foto', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('ficheiro', models.FileField(upload_to='geologia/logging/anexos/')),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_logs_geologicos', to='plataforma.empresa')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='geologia.loggeologicofuro')),
            ],
            options={
                'verbose_name': 'Anexo do Log Geologico',
                'verbose_name_plural': 'Anexos dos Logs Geologicos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MissaoDroneFuro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('equipamento', models.CharField(default='DJI Mini 4 Pro', max_length=100)),
                ('status', models.CharField(choices=[('planeada', 'Planeada'), ('executada', 'Executada'), ('importada', 'Importada'), ('analisada', 'Analisada')], default='planeada', max_length=20)),
                ('data_voo', models.DateField(default=django.utils.timezone.now)),
                ('piloto_nome', models.CharField(blank=True, max_length=120)),
                ('objetivo', models.TextField(blank=True)),
                ('altitude_maxima_m', models.FloatField(default=0.0)),
                ('duracao_minutos', models.PositiveIntegerField(default=0)),
                ('area_coberta_m2', models.FloatField(blank=True, null=True)),
                ('latitude_centro', models.FloatField(blank=True, null=True)),
                ('longitude_centro', models.FloatField(blank=True, null=True)),
                ('ortomosaico', models.FileField(blank=True, null=True, upload_to='geologia/drone/ortomosaicos/')),
                ('modelo_3d', models.FileField(blank=True, null=True, upload_to='geologia/drone/modelos_3d/')),
                ('log_voo', models.FileField(blank=True, null=True, upload_to='geologia/drone/logs/')),
                ('metadados_voo', models.JSONField(blank=True, default=dict)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes_drone_geologia', to='plataforma.empresa')),
                ('furo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes_drone_geologia', to='projetos.furo')),
            ],
            options={
                'verbose_name': 'Missao de Drone do Furo',
                'verbose_name_plural': 'Missoes de Drone dos Furos',
                'ordering': ['-data_voo', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='loggeologicofuro',
            name='missao_drone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_geologicos', to='geologia.missaodronefuro'),
        ),
    ]
