# Generated by Django 6.0.4 on 2026-04-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missaodronefuro',
            name='altitude_rth_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='app_origem',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='bateria_fim_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='bateria_inicio_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='firmware',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='modo_captura',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='numero_fotos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='numero_videos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='ponto_descolagem_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='ponto_descolagem_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='relatorio_processamento',
            field=models.FileField(blank=True, null=True, upload_to='geologia/drone/processamento/'),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='tipo_missao',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='missaodronefuro',
            name='velocidade_max_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
