# Generated by Django 6.0.4 on 2026-04-22 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologia', '0002_missaodronefuro_altitude_rth_m_and_more'),
        ('plataforma', '0011_empresa_valor_total_ganho_furo'),
        ('projetos', '0010_importacaofuro3dexterna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneOperacaoTempoReal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipamento', models.CharField(default='DJI Mini 4 Pro', max_length=100)),
                ('nome_operacao', models.CharField(default='Centro de controlo DJI', max_length=160)),
                ('estado_conexao', models.CharField(choices=[('desligado', 'Desligado'), ('pronto', 'Pronto'), ('em_voo', 'Em voo'), ('em_missao', 'Em missão'), ('erro', 'Erro')], default='desligado', max_length=20)),
                ('live_view_url', models.URLField(blank=True)),
                ('frame_snapshot_url', models.URLField(blank=True)),
                ('latitude_atual', models.FloatField(blank=True, null=True)),
                ('longitude_atual', models.FloatField(blank=True, null=True)),
                ('altitude_atual_m', models.FloatField(blank=True, null=True)),
                ('velocidade_atual_ms', models.FloatField(blank=True, null=True)),
                ('heading_graus', models.FloatField(blank=True, null=True)),
                ('bateria_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('sinal_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('satelites_gps', models.PositiveIntegerField(blank=True, null=True)),
                ('gravacao_ativa', models.BooleanField(default=False)),
                ('alvo_latitude', models.FloatField(blank=True, null=True)),
                ('alvo_longitude', models.FloatField(blank=True, null=True)),
                ('alvo_altitude_m', models.FloatField(default=35.0)),
                ('ultimo_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacoes_drone_tempo_real', to='plataforma.empresa')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_drone_tempo_real', to='projetos.furo')),
            ],
            options={
                'verbose_name': 'Operação drone em tempo real',
                'verbose_name_plural': 'Operações drone em tempo real',
                'ordering': ['-atualizado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DroneComandoOperacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_comando', models.CharField(choices=[('goto', 'Ir para ponto'), ('capturar_foto', 'Capturar foto'), ('iniciar_video', 'Iniciar vídeo'), ('parar_video', 'Parar vídeo'), ('rth', 'Return to home'), ('pairar', 'Pairar'), ('sincronizar', 'Sincronizar estado')], max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('executado', 'Executado'), ('cancelado', 'Cancelado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('latitude_alvo', models.FloatField(blank=True, null=True)),
                ('longitude_alvo', models.FloatField(blank=True, null=True)),
                ('altitude_alvo_m', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resposta_execucao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandos_drone_operacao', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos_drone_operacao', to='plataforma.empresa')),
                ('operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='geologia.droneoperacaotemporeal')),
            ],
            options={
                'verbose_name': 'Comando do drone',
                'verbose_name_plural': 'Comandos do drone',
                'ordering': ['-criado_em'],
            },
        ),
    ]
