# Generated by Django 6.0.4 on 2026-04-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologia', '0003_droneoperacaotemporeal_dronecomandooperacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneoperacaotemporeal',
            name='bridge_api_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='droneoperacaotemporeal',
            name='bridge_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='droneoperacaotemporeal',
            name='bridge_base_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='droneoperacaotemporeal',
            name='bridge_nome',
            field=models.CharField(blank=True, default='Bridge DJI RC 2', max_length=120),
        ),
        migrations.AddField(
            model_name='droneoperacaotemporeal',
            name='bridge_ultima_sincronizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='droneoperacaotemporeal',
            name='bridge_ultimo_erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='droneoperacaotemporeal',
            name='bridge_ultimo_estado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='droneoperacaotemporeal',
            name='estado_conexao',
            field=models.CharField(choices=[('desligado', 'Desligado'), ('procurando', 'A procurar'), ('pronto', 'Pronto'), ('em_voo', 'Em voo'), ('em_missao', 'Em missão'), ('erro', 'Erro')], default='desligado', max_length=20),
        ),
    ]
