# Generated by Django 6.0.4 on 2026-04-22 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologia', '0006_operacaodronesftemporeal_comandodronesfoperacao'),
        ('plataforma', '0011_empresa_valor_total_ganho_furo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissaoProgramadaDroneSF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=140)),
                ('ativa', models.BooleanField(default=True)),
                ('tipo_frequencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('pontual', 'Pontual')], default='diaria', max_length=20)),
                ('hora_execucao', models.TimeField()),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latitude_alvo', models.FloatField()),
                ('longitude_alvo', models.FloatField()),
                ('altitude_alvo_m', models.FloatField(default=35.0)),
                ('gravar_video', models.BooleanField(default=True)),
                ('captar_foto', models.BooleanField(default=False)),
                ('pairar_no_destino', models.BooleanField(default=False)),
                ('regressar_base', models.BooleanField(default=True)),
                ('ativar_sensores', models.BooleanField(default=True)),
                ('usar_live_view', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('ultima_execucao_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes_programadas', to='geologia.dronesf')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes_programadas_drone_sf', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Missão programada do Drone S_F',
                'verbose_name_plural': 'Missões programadas do Drone S_F',
                'ordering': ['ativa', 'hora_execucao', 'nome'],
            },
        ),
    ]
