# Generated by Django 6.0.4 on 2026-05-03 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologia', '0007_missaoprogramadadronesf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeologicofuro',
            name='observacao_validacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loggeologicofuro',
            name='status_validacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='loggeologicofuro',
            name='validado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loggeologicofuro',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_geologicos_validados', to=settings.AUTH_USER_MODEL),
        ),
    ]
