# Generated by Django 6.0.4 on 2026-05-10 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geologia', '0008_loggeologicofuro_observacao_validacao_and_more'),
        ('plataforma', '0018_empresa_compliance_score_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteCartograficaGeologica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('pais_regiao', models.CharField(blank=True, max_length=120)),
                ('tipo_servico', models.CharField(choices=[('wms', 'WMS'), ('tile', 'Tile XYZ')], default='wms', max_length=10)),
                ('url_servico', models.URLField()),
                ('layer_names', models.CharField(blank=True, max_length=255)),
                ('attribution', models.CharField(blank=True, max_length=255)),
                ('formato_imagem', models.CharField(blank=True, default='image/png', max_length=50)),
                ('transparencia', models.BooleanField(default=True)),
                ('opacidade', models.FloatField(default=0.75)),
                ('visivel_por_defeito', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontes_cartograficas_geologicas_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes_cartograficas_geologicas', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Fonte Cartográfica Geológica',
                'verbose_name_plural': 'Fontes Cartográficas Geológicas',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
