# Generated by Django 6.0.4 on 2026-05-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geologia", "0009_fontecartograficageologica"),
    ]

    operations = [
        migrations.AddField(
            model_name="fontecartograficageologica",
            name="centro_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fontecartograficageologica",
            name="centro_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fontecartograficageologica",
            name="zoom_inicial",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
