# Generated by Django 6.0.3 on 2026-03-30 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='Furo', max_length=200)),
                ('profundidade', models.FloatField(default=0.0)),
                ('inclinacao', models.FloatField(default=0.0)),
                ('azimute', models.FloatField(default=0.0)),
                ('magnetismo', models.FloatField(default=0.0)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('altitude', models.FloatField(default=0.0)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('localizacao_lat', models.FloatField(default=0.0)),
                ('localizacao_lon', models.FloatField(default=0.0)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pausado', 'Pausado'), ('concluido', 'Concluído')], default='ativo', max_length=20)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='rochas/')),
                ('profundidade', models.FloatField()),
                ('inclinacao', models.FloatField()),
                ('azimute', models.FloatField()),
                ('tipo_rocha', models.CharField(blank=True, max_length=100)),
                ('cor', models.CharField(default='gray', max_length=20)),
                ('dureza', models.FloatField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('furo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='projetos.furo')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.FloatField(default=0.0)),
                ('quantidade', models.IntegerField(default=0)),
                ('diametro', models.FloatField(default=0.0)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(default='Em estoque', max_length=50)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(default=0.0)),
                ('estado', models.CharField(default='Operacional', max_length=50)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='projetos.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='furo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furos', to='projetos.projeto'),
        ),
        migrations.CreateModel(
            name='Empregados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('funcao', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empregados', to='projetos.projeto')),
            ],
        ),
    ]
