# Generated by Django 6.0.3 on 2026-04-16 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='data_fim',
            new_name='data_fim_proj',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='projeto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='data_inicio_proj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
