# Generated by Django 6.0.3 on 2026-04-12 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpregadoFuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('sondador', 'Sondador'), ('sondador_1', 'Sondador 1ª'), ('sondador_2', 'Sondador 2ª'), ('sondador_3', 'Sondador 3ª'), ('ajudante_sondador', 'Ajudante de Sondador'), ('ajudante_sondador_1', 'Ajudante Sondador 1ª'), ('ajudante_sondador_2', 'Ajudante Sondador 2ª'), ('ajudante_sondador_3', 'Ajudante Sondador 3ª'), ('mecanico', 'Mecânico'), ('ajudante_mecanico', 'Ajudante Mecânico'), ('administrador', 'Administrador'), ('encarregado_obra', 'Encarregado de Obra'), ('chefe_turno', 'Chefe de Turno'), ('geologo', 'Geólogo'), ('supervisor', 'Supervisor'), ('fiscal_cliente', 'Fiscal do Cliente'), ('tecnico_seguranca', 'Técnico de Segurança'), ('almoxarife', 'Almoxarife'), ('motorista', 'Motorista'), ('outro', 'Outro')], default='ajudante_sondador', max_length=50)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes_furos', to='projetos.empregados')),
                ('furo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes_empregados', to='projetos.furo')),
            ],
            options={
                'verbose_name': 'Empregado no Furo',
                'verbose_name_plural': 'Empregados nos Furos',
                'ordering': ['-ativo', 'empregado__nome'],
                'unique_together': {('empregado', 'furo')},
            },
        ),
    ]
