# Generated by Django 6.0.3 on 2026-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregados',
            name='alertas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='empregados',
            name='contrato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='curriculo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='data_fim_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='data_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='doc_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='horas_diarias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='horas_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='horas_mensais',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='horas_trabalhadas_mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='morada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='nib',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='nif',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='projetos_ativos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='empregados',
            name='salario',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furo',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='furo',
            name='estado',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('parado', 'Parado'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='furo',
            name='ficheiros',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='furo',
            name='imagens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='furo',
            name='local_sondagem',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='furo',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='furo',
            name='medicoes_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='furo',
            name='metros_furados',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furo',
            name='metros_furados_diario',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='furo',
            name='planeamento',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='furo',
            name='profundidade_alvo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furo',
            name='profundidade_atual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furo',
            name='profundidade_final',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furo',
            name='relatorios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='furo',
            name='tipo',
            field=models.CharField(choices=[('fundo', 'Fundo'), ('superficie', 'Superfície')], default='fundo', max_length=20),
        ),
        migrations.AddField(
            model_name='furo',
            name='trabalhadores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maquina',
            name='ano_registo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maquina',
            name='data_iuc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='data_registo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='data_revisao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='data_seguro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='despesas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maquina',
            name='km',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maquina',
            name='seguro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='material',
            name='faturas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicao',
            name='magnetismo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='nome_furo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cidade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='projeto',
            name='furos_json',
            field=models.JSONField(blank=True, default=list, help_text='Lista de furos em JSON'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='pais',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('avariada', 'Avariada'), ('reparacao', 'Reparação'), ('sucata', 'Sucata'), ('parada', 'Parada')], default='operacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado',
            field=models.CharField(choices=[('em_estoque', 'Em estoque'), ('sem_stock', 'Sem stock'), ('recebido', 'Recebido'), ('encomendado', 'Encomendado')], default='em_estoque', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='azimute',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='inclinacao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='profundidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
