# Generated by Django 6.0.3 on 2026-04-02 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_empregados_alertas_empregados_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furo',
            name='profundidade',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='furos_json',
        ),
        migrations.AddField(
            model_name='empregados',
            name='furos',
            field=models.ManyToManyField(blank=True, related_name='empregados', to='projetos.furo'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='furos',
            field=models.ManyToManyField(blank=True, related_name='maquinas', to='projetos.furo'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='projeto_atual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='maquinas', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='material',
            name='furo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='projetos.furo'),
        ),
        migrations.AlterField(
            model_name='furo',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='furo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='furo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='localizacao_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='localizacao_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
