# Generated by Django 6.0.3 on 2026-04-13 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_empregadofuro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConfiguracaoPerfuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('apagado', 'Apagado')], max_length=20)),
                ('comprimento_tubo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprimento_karoutier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprimento_acrescento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprimento_calibrador', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprimento_record', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprimento_bit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprimento_caixa_mola', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprimento_tubo_interior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comprimento_cabeca_interior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a alteração efetuada.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_alterados_configuracao', to=settings.AUTH_USER_MODEL)),
                ('configuracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='projetos.configuracaoperfuracaoempregado')),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_configuracao', to='projetos.empregados')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_configuracao', to='projetos.furo')),
            ],
            options={
                'verbose_name': 'Histórico de Configuração de Perfuração',
                'verbose_name_plural': 'Históricos de Configuração de Perfuração',
                'ordering': ['-criado_em'],
            },
        ),
    ]
