# Generated by Django 6.0.4 on 2026-04-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_data_fim_projeto_data_fim_proj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoperfuracaoempregado',
            name='quantidade_calibrador',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuracaoperfuracaoempregado',
            name='quantidade_karoutier',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuracaoperfuracaoempregado',
            name='quantidade_record',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuracaoperfuracaoempregado',
            name='quantidade_tubo_interior',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoperfuracao',
            name='quantidade_calibrador',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoperfuracao',
            name='quantidade_karoutier',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoperfuracao',
            name='quantidade_record',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoperfuracao',
            name='quantidade_tubo_interior',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
