# Generated by Django 6.0.3 on 2026-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_historicoconfiguracaoperfuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='funcao',
            field=models.CharField(blank=True, choices=[('Perfurador1ª', 'Perfurador 1ª'), ('Perfurador2ª', 'Perfurador 2ª'), ('Perfurador3ª', 'Perfurador 3ª'), ('ajudante_Perfurador1', 'Ajudante de Perfurador 1'), ('ajudante_Perfurador2', 'Ajudante de Perfurador 2'), ('ajudante_Perfurador', 'Ajudante de Perfurador'), ('mecanico', 'Mecânico'), ('ajudante_mecanico', 'Ajudante Mecânico'), ('administrador', 'Administrador'), ('encarregado_obra', 'Encarregado de Obra'), ('chefe_turno', 'Chefe de Turno'), ('geologo', 'Geólogo'), ('supervisor', 'Supervisor'), ('tecnico_seguranca', 'Técnico de Segurança'), ('almoxarife', 'Almoxarife'), ('motorista', 'Motorista'), ('outro', 'Outro')], max_length=50, null=True),
        ),
    ]
