# Generated by Django 6.0.3 on 2026-04-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_remove_furo_profundidade_remove_maquina_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
