# Generated by Django 6.0.3 on 2026-04-13 14:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_empregados_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registodiarioempregado',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RegistoDiarioFotoAmostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='registos/amostras/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('registo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_amostra', to='projetos.registodiarioempregado')),
            ],
            options={
                'verbose_name': 'Foto de Amostra do Registo',
                'verbose_name_plural': 'Fotos de Amostra do Registo',
                'ordering': ['-data_upload'],
            },
        ),
    ]
