# Generated by Django 6.0.3 on 2026-04-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_medicao_altitude_medicao_latitude_medicao_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='furo',
            name='profundidade_inicial',
            field=models.FloatField(default=0.0),
        ),
    ]
