# Generated by Django 6.0.4 on 2026-04-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_configuracaoperfuracaoempregado_quantidade_acrescento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoperfuracaoempregado',
            name='comprimento_acrescento_tubo_interior',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoperfuracao',
            name='comprimento_acrescento_tubo_interior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
