# Generated by Django 6.0.4 on 2026-04-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_configuracaoperfuracaoempregado_comprimento_acrescento_tubo_interior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoperfuracaoempregado',
            name='quantidade_acrescento_tubo_interior',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaoperfuracao',
            name='quantidade_acrescento_tubo_interior',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
