# Generated by Django 6.0.3 on 2026-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_furo_profundidade_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furo',
            name='origem_este',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furo',
            name='origem_norte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furo',
            name='origem_tvd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furo',
            name='sistema_coordenadas',
            field=models.CharField(default='local', max_length=50),
        ),
    ]
