# Generated by Django 6.0.3 on 2026-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_registodiarioempregado_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furo',
            name='total_horas',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='azimute_furo_antes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='azimute_furo_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='azimute_furo_depois',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_trabalhadas_furo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='inclinacao_furo_antes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='inclinação_furo_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='inclinação_furo_depois',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='profundidade_furo_antes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='profundidade_furo_atual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='profundidade_furo_depois',
            field=models.FloatField(default=0.0),
        ),
    ]
