# Generated by Django 6.0.3 on 2026-04-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_furo_origem_este_furo_origem_norte_furo_origem_tvd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furo',
            name='sistema_coordenadas',
            field=models.CharField(choices=[('local', 'Local'), ('utm', 'UTM'), ('wgs84', 'WGS84')], default='local', max_length=50),
        ),
    ]
