# Generated by Django 6.0.3 on 2026-04-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_furo_total_horas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registodiarioempregado',
            old_name='inclinação_furo_atual',
            new_name='inclinacao_furo_atual',
        ),
        migrations.RenameField(
            model_name='registodiarioempregado',
            old_name='inclinação_furo_depois',
            new_name='inclinacao_furo_depois',
        ),
        migrations.AddField(
            model_name='furo',
            name='horas_trabalhadas_furo',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='furo',
            name='total_horas',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
