# Generated by Django 6.0.4 on 2026-04-21 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_movimentofinanceiroplataforma_categoria_and_more'),
        ('projetos', '0006_configuracaoperfuracaoempregado_quantidade_acrescento_tubo_interior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_tipo', models.CharField(blank=True, max_length=50)),
                ('tipo_evento', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Eliminação')], max_length=20)),
                ('entidade_tipo', models.CharField(max_length=100)),
                ('entidade_id', models.CharField(max_length=100)),
                ('entidade_label', models.CharField(blank=True, max_length=255)),
                ('snapshot_antes', models.JSONField(blank=True, default=dict)),
                ('snapshot_depois', models.JSONField(blank=True, default=dict)),
                ('metricas', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analytics_projetos', to=settings.AUTH_USER_MODEL)),
                ('empregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analytics', to='projetos.empregados')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_analytics', to='plataforma.empresa')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analytics', to='projetos.furo')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analytics', to='projetos.maquina')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analytics', to='projetos.material')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_analytics', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Evento Analytics',
                'verbose_name_plural': 'Eventos Analytics',
                'ordering': ['-criado_em'],
            },
        ),
    ]
