# Generated by Django 6.0.3 on 2026-04-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_alter_furo_sistema_coordenadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregados',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='empregados',
            name='projetos_ativos',
        ),
        migrations.CreateModel(
            name='EmpregadoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes_projetos', to='projetos.empregados')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empregado_projetos', to='projetos.projeto')),
            ],
            options={
                'unique_together': {('empregado', 'projeto', 'data_inicio')},
            },
        ),
    ]
