# Generated by Django 6.0.4 on 2026-04-21 10:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_eventoanalytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_inicio_atividade', models.DateField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('doc_id', models.BigIntegerField(blank=True, null=True)),
                ('nib', models.CharField(blank=True, max_length=50, null=True)),
                ('morada', models.CharField(blank=True, max_length=200, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('nif', models.BigIntegerField(blank=True, null=True)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='individuais/curriculos/')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='individuais/documentos/')),
                ('biografia', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('total_horas', models.FloatField(default=0.0)),
                ('total_metros', models.FloatField(default=0.0)),
                ('total_registos', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_registo', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_individual', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuais',
                'ordering': ['nome'],
            },
        ),
    ]
