# Generated by Django 6.0.3 on 2026-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_rename_inclinação_furo_atual_registodiarioempregado_inclinacao_furo_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registodiarioempregado',
            name='total_horas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='registodiarioempregado',
            name='horas_trabalhadas_furo',
            field=models.FloatField(default=0.0),
        ),
    ]
