# Generated by Django 6.0.3 on 2026-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_remove_empregados_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregados',
            name='horas_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
