# Generated by Django 6.0.3 on 2026-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_registodiarioempregado_total_horas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furo',
            name='horas_trabalhadas_furo',
        ),
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='azimute_furo_atual',
        ),
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='inclinacao_furo_atual',
        ),
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='profundidade_furo_atual',
        ),
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='total_horas',
        ),
        migrations.AddField(
            model_name='furo',
            name='azimute_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furo',
            name='inclinacao_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registodiarioempregado',
            name='horas_trabalhadas_furo',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
