# Generated by Django 6.0.4 on 2026-04-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_individual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='nib',
        ),
    ]
