# Generated by Django 6.0.3 on 2026-04-13 18:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_remove_furo_horas_trabalhadas_furo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furo',
            options={'ordering': ['-data', 'nome'], 'verbose_name': 'Furo', 'verbose_name_plural': 'Furos'},
        ),
        migrations.AlterModelOptions(
            name='medicao',
            options={'ordering': ['-criado_em', '-profundidade_medida'], 'verbose_name': 'Medição', 'verbose_name_plural': 'Medições'},
        ),
        migrations.RenameField(
            model_name='furo',
            old_name='azimute_atual',
            new_name='azimute_planeado_atual',
        ),
        migrations.RenameField(
            model_name='furo',
            old_name='azimute',
            new_name='azimute_planeado_inicial',
        ),
        migrations.RenameField(
            model_name='furo',
            old_name='inclinacao_atual',
            new_name='inclinacao_planeada_atual',
        ),
        migrations.RenameField(
            model_name='furo',
            old_name='inclinacao',
            new_name='inclinacao_planeada_inicial',
        ),
        migrations.RenameField(
            model_name='furo',
            old_name='profundidade_alvo',
            new_name='profundidade_alvo_inicial',
        ),
        migrations.RenameField(
            model_name='furo',
            old_name='profundidade_final',
            new_name='profundidade_maxima_atingida',
        ),
        migrations.RenameField(
            model_name='medicao',
            old_name='azimute',
            new_name='azimute_real_medido',
        ),
        migrations.RenameField(
            model_name='medicao',
            old_name='inclinacao',
            new_name='inclinacao_real_medida',
        ),
        migrations.RenameField(
            model_name='medicao',
            old_name='nome_furo',
            new_name='nome_furo_snapshot',
        ),
        migrations.RenameField(
            model_name='medicao',
            old_name='profundidade',
            new_name='profundidade_medida',
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='azimute_furo_antes',
        ),
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='azimute_furo_depois',
        ),
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='inclinacao_furo_antes',
        ),
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='inclinacao_furo_depois',
        ),
        migrations.AddField(
            model_name='furo',
            name='azimute_real_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furo',
            name='inclinacao_real_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furo',
            name='profundidade_alvo_atual',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='medicao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='azimute_planeado_atual_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='azimute_planeado_inicial_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicao',
            name='inclinacao_planeada_atual_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='inclinacao_planeada_inicial_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='profundidade_alvo_atual_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='profundidade_alvo_inicial_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='azimute_planeado_atual_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='azimute_planeado_inicial_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='azimute_real_atual_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='inclinacao_planeada_atual_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='inclinacao_planeada_inicial_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='inclinacao_real_atual_furo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='profundidade_alvo_atual_furo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='profundidade_alvo_inicial_furo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='medicao',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registodiarioempregado',
            name='furo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_furo', to='projetos.furo'),
        ),
        migrations.AlterField(
            model_name='registodiarioempregado',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_projeto', to='projetos.projeto'),
        ),
    ]
