# Generated by Django 6.0.3 on 2026-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_empregados_horas_total_empregados_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
