# Generated by Django 6.0.3 on 2026-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_alter_empregados_nome_alter_empregados_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='nome',
            field=models.CharField(blank=True, default='Empregado', max_length=200),
        ),
    ]
