# Generated by Django 6.0.4 on 2026-04-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_furoversao'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasuser',
            name='paleta',
            field=models.CharField(choices=[('industrial-blue', 'Industrial Azul'), ('earth-drill', 'Terra Drill'), ('graphite-tech', 'Grafite Tech'), ('sandstone', 'Sandstone')], default='industrial-blue', max_length=30),
        ),
    ]
