# Generated by Django 6.0.3 on 2026-04-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_alter_empregados_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='empregados/contratos/'),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='empregados/curriculos/'),
        ),
        migrations.CreateModel(
            name='EmpregadoFicheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('bi', 'BI / Cartão de Cidadão'), ('nib', 'NIB / IBAN'), ('contrato', 'Contrato'), ('curriculo', 'Currículo'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('ficheiro', models.FileField(upload_to='empregados/ficheiros/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='projetos.empregados')),
            ],
        ),
    ]
