# Generated by Django 6.0.3 on 2026-04-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_alter_empregados_contrato_alter_empregados_curriculo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empregadoprojeto',
            options={'ordering': ['-ativo', '-data_inicio']},
        ),
        migrations.AlterField(
            model_name='empregadoficheiro',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
