# Generated by Django 6.0.4 on 2026-04-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0012_preferenciasuser_paleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciasuser',
            name='idioma',
            field=models.CharField(choices=[('pt-pt', 'Português'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('zh-hans', '简体中文')], default='pt-pt', max_length=10),
        ),
        migrations.AlterField(
            model_name='preferenciasuser',
            name='paleta',
            field=models.CharField(choices=[('industrial-blue', 'Aço Profissional'), ('earth-drill', 'Terra Técnica'), ('graphite-tech', 'Grafite Elegante'), ('sandstone', 'Areia Industrial')], default='industrial-blue', max_length=30),
        ),
    ]
