# Generated by Django 6.0.3 on 2026-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_alter_empregadoprojeto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='horas_diarias',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='horas_extra',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='horas_mensais',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='horas_total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='empregados',
            name='horas_trabalhadas_mes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
