# Generated by Django 6.0.4 on 2026-04-26 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_alter_preferenciasuser_idioma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoPlataforma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avaliacao', models.CharField(choices=[('excelente', 'Excelente'), ('boa', 'Boa'), ('regular', 'Regular'), ('fraca', 'Fraca')], max_length=20)),
                ('opiniao', models.TextField(blank=True)),
                ('sugestoes', models.TextField()),
                ('email_destino', models.EmailField(blank=True, max_length=254)),
                ('enviado_por_email', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_plataforma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugestão da Plataforma',
                'verbose_name_plural': 'Sugestões da Plataforma',
                'ordering': ['-criado_em'],
            },
        ),
    ]
