# Generated by Django 6.0.4 on 2026-04-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0014_sugestaoplataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasuser',
            name='tamanho_texto',
            field=models.CharField(choices=[('normal', 'Normal'), ('grande', 'Grande'), ('extra-grande', 'Extra Grande')], default='normal', max_length=20),
        ),
    ]
