# Generated by Django 6.0.3 on 2026-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_empregados_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregados',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empregados',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empregados',
            name='data_registo',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
