# Generated by Django 6.0.4 on 2026-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_preferenciasuser_tamanho_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='furo',
            name='data_fim_operacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='furo',
            name='data_inicio_operacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
