# Generated by Django 6.0.3 on 2026-04-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_empregados_aprovado_empregados_data_aprovacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistoDiarioEmpregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horas_trabalhadas', models.FloatField(default=0.0)),
                ('metros_furados', models.FloatField(default=0.0)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_diarios', to='projetos.empregados')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_empregados', to='projetos.furo')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_empregados', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Registo Diário do Empregado',
                'verbose_name_plural': 'Registos Diários dos Empregados',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
