# Generated by Django 6.0.4 on 2026-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_furo_data_fim_operacao_furo_data_inicio_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furoversao',
            name='origem',
            field=models.CharField(choices=[('criado', 'Criado'), ('atualizado', 'Atualizado'), ('medicao', 'Medição'), ('recalculo', 'Recalculo'), ('concluido', 'Concluído'), ('reativado', 'Reativado'), ('migracao', 'Migração')], default='atualizado', max_length=20),
        ),
    ]
