# Generated by Django 6.0.3 on 2026-04-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0017_registodiarioempregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registodiarioempregado',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='hora_fim_pausa',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='hora_inicio_pausa',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='hora_pausa',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
