# Generated by Django 6.0.4 on 2026-04-29 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_furoarquivadoplataforma'),
        ('projetos', '0017_alter_furoversao_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaAvaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_reparacao', 'Em reparação'), ('resolvida', 'Resolvida')], default='aberta', max_length=20)),
                ('descricao', models.TextField()),
                ('solucao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina_avarias', to='plataforma.empresa')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_avarias', to='projetos.furo')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avarias', to='projetos.maquina')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_avarias', to='projetos.projeto')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_reportadas_maquina', to='projetos.empregados')),
            ],
            options={
                'verbose_name': 'Avaria da máquina',
                'verbose_name_plural': 'Avarias da máquina',
                'ordering': ['-data_inicio', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MaquinaEventoOperacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('alocacao_projeto', 'Alocação a projeto'), ('alocacao_furo', 'Alocação a furo'), ('operacao_turno', 'Operação em turno'), ('avaria_reportada', 'Avaria reportada'), ('avaria_resolvida', 'Avaria resolvida')], max_length=30)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('metros_furados', models.FloatField(default=0.0)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_eventos_operacionais', to='projetos.empregados')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina_eventos_operacionais', to='plataforma.empresa')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_eventos_operacionais', to='projetos.furo')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_operacionais', to='projetos.maquina')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_eventos_operacionais', to='projetos.projeto')),
                ('registo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquina_eventos_operacionais', to='projetos.registodiarioempregado')),
            ],
            options={
                'verbose_name': 'Evento operacional da máquina',
                'verbose_name_plural': 'Eventos operacionais da máquina',
                'ordering': ['-data_evento', '-criado_em'],
            },
        ),
    ]
