# Generated by Django 6.0.3 on 2026-04-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0018_registodiarioempregado_hora_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registodiarioempregado',
            name='hora_pausa',
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='editado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='editado_por_empregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='relatorio_foto',
            field=models.ImageField(blank=True, null=True, upload_to='registos_diarios/relatorios/'),
        ),
        migrations.AlterField(
            model_name='registodiarioempregado',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
