# Generated by Django 6.0.4 on 2026-04-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0018_maquinaavaria_maquinaeventooperacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaavaria',
            name='responsavel_empregado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_responsavel_maquina', to='projetos.empregados'),
        ),
    ]
