# Generated by Django 6.0.4 on 2026-05-02 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0019_maquinaavaria_responsavel_empregado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo3DWireframe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('obj', 'OBJ'), ('dxf', 'DXF')], max_length=10)),
                ('ficheiro', models.FileField(upload_to='modelos_3d/wireframe/')),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('resumo_json', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_wireframe_3d', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo 3D Wireframe',
                'verbose_name_plural': 'Modelos 3D Wireframe',
                'ordering': ['-criado_em'],
            },
        ),
    ]
