# Generated by Django 6.0.3 on 2026-04-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0019_remove_registodiarioempregado_hora_pausa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_paragem',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='tipo_paragem',
            field=models.CharField(blank=True, choices=[('', '---------'), ('cliente', 'Cliente'), ('empresa', 'Empresa')], default='', max_length=20),
        ),
    ]
