# Generated by Django 6.0.3 on 2026-04-05 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0020_registodiarioempregado_horas_paragem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='despesas',
        ),
        migrations.AddField(
            model_name='maquina',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='horimetro',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='maquina',
            name='localizacao_atual',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='maquina',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maquina',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ano_registo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='km',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='projeto_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_atuais', to='projetos.projeto'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='valor',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('combustivel', 'Combustível'), ('manutencao', 'Manutenção'), ('pecas', 'Peças'), ('salarios', 'Salários'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('tipo', models.CharField(choices=[('maquina', 'Máquina'), ('projeto', 'Projeto'), ('furo', 'Furo'), ('geral', 'Geral')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.FloatField(default=0.0)),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='despesas/comprovativos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='projetos.furo')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='projetos.maquina')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='projetos.projeto')),
            ],
        ),
    ]
