# Generated by Django 6.0.4 on 2026-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0020_modelo3dwireframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo3dwireframe',
            name='ficheiro',
        ),
        migrations.AddField(
            model_name='modelo3dwireframe',
            name='conteudo_texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
