# Generated by Django 6.0.3 on 2026-04-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0021_remove_maquina_despesas_maquina_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='faturas',
        ),
        migrations.AddField(
            model_name='material',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='material',
            name='localizacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='unidade',
            field=models.CharField(blank=True, default='un', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='diametro',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='material',
            name='furo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='projetos.furo'),
        ),
    ]
