# Generated by Django 6.0.4 on 2026-05-02 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0022_modelo3dblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo3DImplicit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('dominio', models.CharField(blank=True, default='', max_length=100)),
                ('conteudo_texto', models.TextField(blank=True, default='')),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('resumo_json', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_implicit_3d', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo 3D Implícito',
                'verbose_name_plural': 'Modelos 3D Implícitos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
