# Generated by Django 6.0.4 on 2026-05-03 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_furoarquivadoplataforma'),
        ('projetos', '0023_modelo3dimplicit'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo3dblock',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_3d_block', to='plataforma.empresa'),
        ),
        migrations.AddField(
            model_name='modelo3dblock',
            name='origem_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelo3dblock',
            name='origem_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelo3dblock',
            name='origem_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelo3dblock',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_3d_block', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='modelo3dblock',
            name='tamanho_bloco_x',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelo3dblock',
            name='tamanho_bloco_y',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelo3dblock',
            name='tamanho_bloco_z',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='BlockModelCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('centro_x', models.FloatField(default=0.0)),
                ('centro_y', models.FloatField(default=0.0)),
                ('centro_z', models.FloatField(default=0.0)),
                ('litologia', models.CharField(blank=True, default='', max_length=120)),
                ('dureza_media', models.FloatField(blank=True, null=True)),
                ('densidade', models.FloatField(blank=True, null=True)),
                ('teor', models.FloatField(blank=True, null=True)),
                ('distancia_ao_furo', models.FloatField(blank=True, null=True)),
                ('dados_json', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('block_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celulas', to='projetos.modelo3dblock')),
            ],
            options={
                'verbose_name': 'Célula de Block Model',
                'verbose_name_plural': 'Células de Block Model',
                'ordering': ['x', 'y', 'z'],
                'indexes': [models.Index(fields=['block_model', 'x', 'y', 'z'], name='projetos_bl_block_m_f9b66f_idx'), models.Index(fields=['block_model', 'litologia'], name='projetos_bl_block_m_23b7a4_idx')],
            },
        ),
    ]
