# Generated by Django 6.0.3 on 2026-04-05 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0023_levantamentomaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='projetos.projeto'),
        ),
    ]
