# Generated by Django 6.0.3 on 2026-04-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0024_alter_material_projeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levantamentomaterial',
            options={'ordering': ['-data', '-criado_em'], 'verbose_name': 'Levantamento de Material', 'verbose_name_plural': 'Levantamentos de Materiais'},
        ),
    ]
