# Generated by Django 6.0.4 on 2026-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0025_alter_empregadofuro_funcao_alter_empregados_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='custo_por_metro_cliente_override',
            field=models.FloatField(blank=True, help_text='Se definido, este valor substitui o custo por metro global da empresa para este projeto.', null=True),
        ),
    ]
