# Generated by Django 6.0.3 on 2026-04-05 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0025_alter_levantamentomaterial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empregado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes_materiais', to='projetos.empregados')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_materiais', to='projetos.furo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='projetos.material')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_materiais', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Devolução de Material',
                'verbose_name_plural': 'Devoluções de Materiais',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
