# Generated by Django 6.0.3 on 2026-04-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0026_devolucaomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
