# Generated by Django 6.0.3 on 2026-04-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0027_material_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregados',
            name='media_metros_por_dia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='media_metros_por_hora',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='metros_furados_hoje',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='metros_furados_mes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='total_devolucoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='total_furos_trabalhados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='total_levantamentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empregados',
            name='total_metros_furados',
            field=models.FloatField(default=0.0),
        ),
    ]
