# Generated by Django 6.0.4 on 2026-05-04 15:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0030_alter_empregadofuro_funcao_alter_empregados_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('numero_contrato', models.CharField(blank=True, max_length=120)),
                ('contacto_nome', models.CharField(blank=True, max_length=200)),
                ('contacto_email', models.EmailField(blank=True, max_length=254)),
                ('contacto_telefone', models.CharField(blank=True, max_length=40)),
                ('tipo_cobranca', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('projeto', 'Por projeto')], default='mensal', max_length=20)),
                ('valor_contratado', models.FloatField(default=0.0)),
                ('moeda', models.CharField(default='EUR', max_length=8)),
                ('sla_resposta_horas', models.PositiveIntegerField(default=24)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('terminado', 'Terminado')], default='ativo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_contratos', to='plataforma.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_contratos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Cliente/Contrato',
                'verbose_name_plural': 'Clientes/Contratos',
                'ordering': ['nome_cliente', '-atualizado_em'],
            },
        ),
    ]
