# Generated by Django 6.0.4 on 2026-05-04 19:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0031_clientecontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneamentoTurno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('extra', 'Extra')], default='manha', max_length=20)),
                ('estado', models.CharField(choices=[('planeado', 'Planeado'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planeado', max_length=20)),
                ('prioridade', models.PositiveSmallIntegerField(default=2)),
                ('objetivo', models.CharField(blank=True, max_length=220)),
                ('notas', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planeamentos_turnos', to='projetos.empregados')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeamentos_turnos', to='plataforma.empresa')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planeamentos_turnos', to='projetos.furo')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planeamentos_turnos', to='projetos.maquina')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planeamentos_turnos', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Planeamento de Turno',
                'verbose_name_plural': 'Planeamento de Turnos',
                'ordering': ['-data_inicio', 'turno', '-atualizado_em'],
            },
        ),
    ]
