# Generated by Django 6.0.4 on 2026-05-04 21:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0034_pedidocompra_notificacaogestao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistHSE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('data_check', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('conforme', 'Conforme'), ('nao_conforme', 'Não conforme')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_hse', to='plataforma.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_hse', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_hse', to='projetos.empregados')),
            ],
            options={
                'verbose_name': 'Checklist HSE',
                'verbose_name_plural': 'Checklists HSE',
                'ordering': ['-data_check', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IncidenteSeguranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True)),
                ('gravidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('investigacao', 'Em investigação'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('data_incidente', models.DateField(default=django.utils.timezone.localdate)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_seguranca', to='plataforma.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_seguranca', to='projetos.projeto')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to='projetos.empregados')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_responsavel', to='projetos.empregados')),
            ],
            options={
                'verbose_name': 'Incidente de segurança',
                'verbose_name_plural': 'Incidentes de segurança',
                'ordering': ['status', '-data_incidente', '-criado_em'],
            },
        ),
    ]
