# Generated by Django 6.0.4 on 2026-05-05 08:13

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0035_checklisthse_incidenteseguranca'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoRelatorioExecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('frequencia', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='semanal', max_length=20)),
                ('hora_execucao', models.TimeField(default=datetime.time(8, 0))),
                ('dia_semana', models.PositiveSmallIntegerField(default=0)),
                ('dia_mes', models.PositiveSmallIntegerField(default=1)),
                ('destinos', models.TextField(blank=True, help_text='Emails separados por vírgula/ponto e vírgula.')),
                ('incluir_csv', models.BooleanField(default=True)),
                ('incluir_xlsx', models.BooleanField(default=True)),
                ('ultimo_envio_em', models.DateTimeField(blank=True, null=True)),
                ('proximo_envio_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento_relatorio_executivo', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Agendamento de relatório executivo',
                'verbose_name_plural': 'Agendamentos de relatório executivo',
            },
        ),
    ]
