# Generated by Django 6.0.4 on 2026-05-05 09:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0036_agendamentorelatorioexecutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=180)),
                ('contacto_nome', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=60)),
                ('sla_dias_entrega', models.PositiveIntegerField(default=0)),
                ('avaliacao', models.FloatField(default=0.0)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_compra', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor de compra',
                'verbose_name_plural': 'Fornecedores de compra',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PropostaFornecedorCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_proposto', models.FloatField(default=0.0)),
                ('prazo_entrega_dias', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('selecionada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_compra', to='projetos.fornecedorcompra')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_fornecedor', to='projetos.pedidocompra')),
            ],
            options={
                'verbose_name': 'Proposta de fornecedor',
                'verbose_name_plural': 'Propostas de fornecedor',
                'ordering': ['valor_proposto', 'prazo_entrega_dias', '-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='fornecedorcompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'nome'), name='uniq_fornecedor_compra_empresa_nome'),
        ),
    ]
