# Generated by Django 6.0.4 on 2026-05-05 10:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0037_fornecedorcompra_propostafornecedorcompra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEnvioRelatorioExecutivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('agendado', 'Agendado'), ('executar_agora', 'Executar agora')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], default='sucesso', max_length=20)),
                ('assunto', models.CharField(blank=True, max_length=220)),
                ('destinos', models.TextField(blank=True)),
                ('incluir_csv', models.BooleanField(default=True)),
                ('incluir_xlsx', models.BooleanField(default=True)),
                ('enviados', models.PositiveIntegerField(default=0)),
                ('filtros_json', models.JSONField(blank=True, default=dict)),
                ('resumo_json', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_envios', to='projetos.agendamentorelatorioexecutivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_relatorios_executivos', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Histórico de envio de relatório executivo',
                'verbose_name_plural': 'Histórico de envio de relatórios executivos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
