# Generated by Django 6.0.4 on 2026-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0038_historicoenviorelatorioexecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentorelatorioexecutivo',
            name='incluir_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicoenviorelatorioexecutivo',
            name='incluir_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
