# Generated by Django 6.0.4 on 2026-05-05 10:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0039_agendamentorelatorioexecutivo_incluir_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaHSE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('data_auditoria', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('planeada', 'Planeada'), ('em_curso', 'Em curso'), ('concluida', 'Concluída')], default='planeada', max_length=20)),
                ('resultado', models.CharField(choices=[('conforme', 'Conforme'), ('observacao', 'Observação'), ('nao_conforme', 'Não conforme')], default='observacao', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_hse', to='plataforma.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_hse', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_hse', to='projetos.empregados')),
            ],
            options={
                'verbose_name': 'Auditoria HSE',
                'verbose_name_plural': 'Auditorias HSE',
                'ordering': ['status', '-data_auditoria', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AcaoCorretiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('concluida_em', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_corretivas', to='projetos.checklisthse')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_corretivas', to='plataforma.empresa')),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_corretivas', to='projetos.incidenteseguranca')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_corretivas', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_corretivas', to='projetos.empregados')),
                ('auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_corretivas', to='projetos.auditoriahse')),
            ],
            options={
                'verbose_name': 'Ação corretiva',
                'verbose_name_plural': 'Ações corretivas',
                'ordering': ['status', 'prazo', '-criado_em'],
            },
        ),
    ]
