# Generated by Django 6.0.4 on 2026-05-05 11:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0040_auditoriahse_acaocorretiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaCompliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('documento', 'Documento'), ('relatorio', 'Relatório'), ('outro', 'Outro')], default='documento', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=180)),
                ('ficheiro', models.FileField(upload_to='gestao/compliance/evidencias/')),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('acao_corretiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='projetos.acaocorretiva')),
                ('auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='projetos.auditoriahse')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='projetos.checklisthse')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_compliance_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_compliance', to='plataforma.empresa')),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='projetos.incidenteseguranca')),
            ],
            options={
                'verbose_name': 'Evidência de compliance',
                'verbose_name_plural': 'Evidências de compliance',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FechoAcaoCorretiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fecho', models.DateField(default=django.utils.timezone.localdate)),
                ('resumo_execucao', models.TextField()),
                ('eficaz', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fecho_formal', to='projetos.acaocorretiva')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechos_acoes_corretivas', to='plataforma.empresa')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechos_acoes_corretivas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fecho formal da ação corretiva',
                'verbose_name_plural': 'Fechos formais das ações corretivas',
                'ordering': ['-data_fecho', '-criado_em'],
            },
        ),
    ]
