# Generated by Django 6.0.4 on 2026-05-05 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_empresa_geologia_score_config'),
        ('projetos', '0041_evidenciacompliance_fechoacaocorretiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoPreventiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('concluida_em', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_preventivas', to='projetos.auditoriahse')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_preventivas', to='projetos.checklisthse')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_preventivas', to='plataforma.empresa')),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_preventivas', to='projetos.incidenteseguranca')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_preventivas', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_preventivas', to='projetos.empregados')),
            ],
            options={
                'verbose_name': 'Ação preventiva',
                'verbose_name_plural': 'Ações preventivas',
                'ordering': ['status', 'prazo', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='evidenciacompliance',
            name='acao_preventiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='projetos.acaopreventiva'),
        ),
        migrations.CreateModel(
            name='PlanoAuditoriaHSE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('frequencia', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('proxima_execucao', models.DateField(default=django.utils.timezone.localdate)),
                ('ultima_geracao_em', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_auditoria_hse', to='plataforma.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_auditoria_hse', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_auditoria_hse', to='projetos.empregados')),
            ],
            options={
                'verbose_name': 'Plano de auditoria HSE',
                'verbose_name_plural': 'Planos de auditoria HSE',
                'ordering': ['proxima_execucao', 'titulo'],
            },
        ),
    ]
