# Generated by Django 6.0.4 on 2026-05-05 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_empresa_compliance_score_config'),
        ('projetos', '0042_acaopreventiva_evidenciacompliance_acao_preventiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecontrato',
            name='dias_alerta_vencimento',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='clientecontrato',
            name='periodo_renovacao_meses',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='clientecontrato',
            name='renovacao_automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClienteContratoAdenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True)),
                ('data_adenda', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_adicional', models.FloatField(default=0.0)),
                ('nova_data_fim', models.DateField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('renovacao_automatica', 'Renovação automática')], default='manual', max_length=30)),
                ('ficheiro', models.FileField(blank=True, null=True, upload_to='gestao/clientes_contratos/adendas/')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adendas', to='projetos.clientecontrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_contratos_adendas', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Adenda contratual',
                'verbose_name_plural': 'Adendas contratuais',
                'ordering': ['-data_adenda', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ClienteContratoAnexo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=220)),
                ('ficheiro', models.FileField(upload_to='gestao/clientes_contratos/anexos/')),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='projetos.clientecontrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_contratos_anexos', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Anexo de contrato',
                'verbose_name_plural': 'Anexos de contrato',
                'ordering': ['-criado_em'],
            },
        ),
    ]
