# Generated by Django 6.0.4 on 2026-05-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0043_clientecontrato_dias_alerta_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecontratoadenda',
            name='data_fim_anterior',
            field=models.DateField(blank=True, null=True),
        ),
    ]
