# Generated by Django 6.0.4 on 2026-05-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0044_clientecontratoadenda_data_fim_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecontrato',
            name='dias_alerta_sem_contacto',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='clientecontrato',
            name='proximo_followup_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientecontrato',
            name='ultimo_contacto_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
