# Generated by Django 6.0.4 on 2026-05-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0045_clientecontrato_dias_alerta_sem_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecontrato',
            name='workflow_comercial',
            field=models.CharField(choices=[('estavel', 'Estável'), ('em_negociacao', 'Em negociação'), ('renovacao_pendente', 'Renovação pendente'), ('renovado', 'Renovado'), ('perdido', 'Perdido')], default='estavel', max_length=30),
        ),
    ]
