# Generated by Django 6.0.4 on 2026-05-05 21:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_empresa_compliance_score_config'),
        ('projetos', '0046_clientecontrato_workflow_comercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContratoWorkflowHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('workflow_novo', models.CharField(choices=[('estavel', 'Estável'), ('em_negociacao', 'Em negociação'), ('renovacao_pendente', 'Renovação pendente'), ('renovado', 'Renovado'), ('perdido', 'Perdido')], max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_contratos_workflow_alterados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_workflow', to='projetos.clientecontrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_contratos_workflow_historico', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Histórico de workflow do contrato',
                'verbose_name_plural': 'Histórico de workflow dos contratos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
