# Generated by Django 6.0.4 on 2026-05-05 22:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_empresa_compliance_score_config'),
        ('projetos', '0047_clientecontratoworkflowhistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteComercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('contacto_principal_nome', models.CharField(blank=True, max_length=200)),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254)),
                ('contacto_principal_telefone', models.CharField(blank=True, max_length=40)),
                ('contacto_secundario_nome', models.CharField(blank=True, max_length=200)),
                ('contacto_secundario_email', models.EmailField(blank=True, max_length=254)),
                ('contacto_secundario_telefone', models.CharField(blank=True, max_length=40)),
                ('classificacao_comercial', models.CharField(choices=[('estrategico', 'Estratégico'), ('crescimento', 'Crescimento'), ('estavel', 'Estável'), ('em_risco', 'Em risco'), ('inativo', 'Inativo')], default='estavel', max_length=30)),
                ('notas_comerciais', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_comerciais', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Ficha comercial de cliente',
                'verbose_name_plural': 'Fichas comerciais de clientes',
                'ordering': ['nome_cliente', '-atualizado_em'],
            },
        ),
    ]
