# Generated by Django 6.0.4 on 2026-05-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0048_clientecomercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeamentoturno',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planeamentoturno',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planeamentoturno',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('extra', 'Extra'), ('extra_manha', 'Extra Manhã'), ('extra_tarde', 'Extra Tarde'), ('extra_noite', 'Extra Noite')], default='manha', max_length=20),
        ),
    ]
