# Generated by Django 6.0.4 on 2026-05-06 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0049_planeamentoturno_hora_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaTurno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('extra', 'Extra'), ('extra_manha', 'Extra Manhã'), ('extra_tarde', 'Extra Tarde'), ('extra_noite', 'Extra Noite')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_maquina', to='projetos.maquina')),
            ],
            options={
                'verbose_name': 'Turno da Máquina',
                'verbose_name_plural': 'Turnos da Máquina',
                'ordering': ['turno', '-atualizado_em'],
                'constraints': [models.UniqueConstraint(fields=('maquina', 'turno'), name='unique_turno_por_maquina')],
            },
        ),
    ]
