# Generated by Django 6.0.4 on 2026-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0050_maquinaturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeamentoturno',
            name='nome',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
