# Generated by Django 6.0.4 on 2026-05-06 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0051_planeamentoturno_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='registodiarioempregado',
            name='planeamento_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos_diarios', to='projetos.planeamentoturno'),
        ),
    ]
