# Generated by Django 6.0.4 on 2026-05-06 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_empresa_compliance_score_config'),
        ('projetos', '0052_registodiarioempregado_planeamento_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioTurno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('sonda', models.CharField(blank=True, max_length=120)),
                ('torre', models.CharField(blank=True, max_length=120)),
                ('bomba_injecao', models.CharField(blank=True, max_length=120)),
                ('bomba_captacao', models.CharField(blank=True, max_length=120)),
                ('estaleiro', models.CharField(blank=True, max_length=200)),
                ('numero_sondagem', models.CharField(blank=True, max_length=120)),
                ('inclinacao', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('diametro_furo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('numero_relatorio', models.CharField(blank=True, max_length=120)),
                ('data', models.DateField(blank=True, null=True)),
                ('no_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avanco_turno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('testemunho_recuperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentagem_recuperacao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('furacao_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furacao_fim', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furacao_avanco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furacao_recuperacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furacao_rocha', models.CharField(blank=True, max_length=200)),
                ('furacao_descricao', models.TextField(blank=True)),
                ('manobra', models.CharField(blank=True, max_length=120)),
                ('reaming', models.CharField(blank=True, max_length=120)),
                ('avaria', models.CharField(blank=True, max_length=120)),
                ('horas_paragem', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('medicao_desvio', models.CharField(blank=True, max_length=120)),
                ('cimentacao', models.CharField(blank=True, max_length=120)),
                ('lavar_furo', models.CharField(blank=True, max_length=120)),
                ('polimeros', models.CharField(blank=True, max_length=120)),
                ('varas_presas', models.CharField(blank=True, max_length=120)),
                ('outros', models.CharField(blank=True, max_length=160)),
                ('notas', models.TextField(blank=True)),
                ('entubamento', models.CharField(blank=True, max_length=120)),
                ('especialistas', models.PositiveIntegerField(default=0)),
                ('serventes', models.PositiveIntegerField(default=0)),
                ('horas_trabalho_especialista', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('horas_trabalho_servente', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bit_novo', models.CharField(blank=True, max_length=120)),
                ('bit_velho', models.CharField(blank=True, max_length=120)),
                ('turno', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_turno', to='plataforma.empresa')),
                ('registo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_turno', to='projetos.registodiarioempregado')),
            ],
            options={
                'verbose_name': 'Relatório de Turno',
                'verbose_name_plural': 'Relatórios de Turno',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
