# Generated by Django 6.0.4 on 2026-05-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0053_relatorioturno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioturno',
            name='especialistas',
        ),
        migrations.RemoveField(
            model_name='relatorioturno',
            name='serventes',
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='especialista_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='especialista_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='especialista_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='especialista_4',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='servente_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='servente_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='servente_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='servente_4',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='cimentacao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='lavar_furo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='medicao_desvio',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='reaming',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='varas_presas',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
    ]
