# Generated by Django 6.0.4 on 2026-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0054_remove_relatorioturno_especialistas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioturno',
            name='horas_trabalho_especialista',
        ),
        migrations.RemoveField(
            model_name='relatorioturno',
            name='horas_trabalho_servente',
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_especialista_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_especialista_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_especialista_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_especialista_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_servente_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_servente_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_servente_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_servente_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
