# Generated by Django 6.0.4 on 2026-05-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0055_remove_relatorioturno_horas_trabalho_especialista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioturno',
            name='avaria',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='bit_novo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='entubamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='manobra',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
    ]
