# Generated by Django 6.0.4 on 2026-05-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0056_alter_relatorioturno_avaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorioturno',
            name='bit_velho',
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='avaria_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='avaria_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='bit_novo_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='bit_novo_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='cimentacao_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='cimentacao_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='entubamento_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='entubamento_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='lavar_furo_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='lavar_furo_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='manobra_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='manobra_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='medicao_desvio_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='medicao_desvio_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='outros_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='outros_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='polimeros_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='polimeros_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='reaming_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='reaming_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='varas_presas_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='varas_presas_de',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
