# Generated by Django 6.0.4 on 2026-05-08 17:06

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def normalizar_horas_paragem_para_sim_nao(apps, schema_editor):
    RelatorioTurno = apps.get_model("projetos", "RelatorioTurno")
    for relatorio in RelatorioTurno.objects.all().only("id", "horas_paragem"):
        valor = relatorio.horas_paragem
        if valor in (None, "", "sim", "nao"):
            continue
        try:
            decimal_valor = Decimal(str(valor))
        except (InvalidOperation, TypeError, ValueError):
            relatorio.horas_paragem = ""
        else:
            relatorio.horas_paragem = "sim" if decimal_valor > 0 else ""
        relatorio.save(update_fields=["horas_paragem"])


def reverter_horas_paragem_para_texto_vazio(apps, schema_editor):
    RelatorioTurno = apps.get_model("projetos", "RelatorioTurno")
    RelatorioTurno.objects.filter(horas_paragem__in=["sim", "nao"]).update(horas_paragem="")


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0057_remove_relatorioturno_bit_velho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_paragem_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='horas_paragem_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='horas_paragem',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3),
        ),
        migrations.RunPython(
            normalizar_horas_paragem_para_sim_nao,
            reverter_horas_paragem_para_texto_vazio,
        ),
    ]
