# Generated by Django 6.0.4 on 2026-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0058_relatorioturno_horas_paragem_ate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioturno',
            name='avaria',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='bit_novo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='cimentacao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='entubamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='horas_paragem',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='lavar_furo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='manobra',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='medicao_desvio',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='reaming',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='relatorioturno',
            name='varas_presas',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
    ]
