# Generated by Django 6.0.4 on 2026-05-08 17:22

from django.db import migrations, models


def copiar_polimeros_antigo_para_primeiro_campo(apps, schema_editor):
    RelatorioTurno = apps.get_model('projetos', 'RelatorioTurno')
    for relatorio in RelatorioTurno.objects.exclude(polimeros__in=["", None]):
        relatorio.polimeros_1 = relatorio.polimeros
        relatorio.save(update_fields=["polimeros_1"])


def reverter_copia_polimeros(apps, schema_editor):
    RelatorioTurno = apps.get_model('projetos', 'RelatorioTurno')
    for relatorio in RelatorioTurno.objects.exclude(polimeros_1__in=["", None]):
        relatorio.polimeros = relatorio.polimeros_1
        relatorio.save(update_fields=["polimeros"])


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0059_alter_relatorioturno_avaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioturno',
            name='polimeros_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='polimeros_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='polimeros_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='polimeros_4',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.RunPython(copiar_polimeros_antigo_para_primeiro_campo, reverter_copia_polimeros),
        migrations.RemoveField(
            model_name='relatorioturno',
            name='polimeros',
        ),
    ]
