# Generated by Django 6.0.4 on 2026-05-08 17:35

from django.db import migrations, models


def migrar_polimeros_para_lista(apps, schema_editor):
    RelatorioTurno = apps.get_model('projetos', 'RelatorioTurno')
    for relatorio in RelatorioTurno.objects.all():
        polimeros = []
        for atributo in ("polimeros_1", "polimeros_2", "polimeros_3", "polimeros_4"):
            valor = getattr(relatorio, atributo, "")
            if isinstance(valor, str) and valor.strip():
                polimeros.append(valor.strip())
        relatorio.polimeros = polimeros
        relatorio.save(update_fields=["polimeros"])


def reverter_lista_para_polimeros(apps, schema_editor):
    RelatorioTurno = apps.get_model('projetos', 'RelatorioTurno')
    for relatorio in RelatorioTurno.objects.all():
        polimeros = list(relatorio.polimeros or [])
        for indice, atributo in enumerate(("polimeros_1", "polimeros_2", "polimeros_3", "polimeros_4")):
            setattr(relatorio, atributo, polimeros[indice] if indice < len(polimeros) else "")
        relatorio.save(update_fields=["polimeros_1", "polimeros_2", "polimeros_3", "polimeros_4"])


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0060_remove_relatorioturno_polimeros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioturno',
            name='polimeros',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrar_polimeros_para_lista, reverter_lista_para_polimeros),
        migrations.RemoveField(
            model_name='relatorioturno',
            name='polimeros_1',
        ),
        migrations.RemoveField(
            model_name='relatorioturno',
            name='polimeros_2',
        ),
        migrations.RemoveField(
            model_name='relatorioturno',
            name='polimeros_3',
        ),
        migrations.RemoveField(
            model_name='relatorioturno',
            name='polimeros_4',
        ),
    ]
