# Generated by Django 6.0.4 on 2026-05-08 18:37

from django.db import migrations, models


def migrar_relatorio_turno_para_registo(apps, schema_editor):
    RegistoDiarioEmpregado = apps.get_model("projetos", "RegistoDiarioEmpregado")
    RelatorioTurno = apps.get_model("projetos", "RelatorioTurno")

    campos_diretos = [
        "cliente",
        "sonda",
        "torre",
        "bomba_injecao",
        "bomba_captacao",
        "estaleiro",
        "numero_sondagem",
        "inclinacao",
        "diametro_furo",
        "numero_relatorio",
        "no_inicio",
        "no_final",
        "avanco_turno",
        "testemunho_recuperado",
        "percentagem_recuperacao",
        "furacao_inicio",
        "furacao_fim",
        "furacao_avanco",
        "furacao_recuperacao",
        "furacao_rocha",
        "furacao_descricao",
        "manobra",
        "manobra_de",
        "manobra_ate",
        "reaming",
        "reaming_de",
        "reaming_ate",
        "avaria",
        "avaria_de",
        "avaria_ate",
        "horas_paragem_de",
        "horas_paragem_ate",
        "medicao_desvio",
        "medicao_desvio_de",
        "medicao_desvio_ate",
        "cimentacao",
        "cimentacao_de",
        "cimentacao_ate",
        "lavar_furo",
        "lavar_furo_de",
        "lavar_furo_ate",
        "polimeros",
        "polimeros_de",
        "polimeros_ate",
        "varas_presas",
        "varas_presas_de",
        "varas_presas_ate",
        "outros",
        "outros_de",
        "outros_ate",
        "notas",
        "entubamento",
        "entubamento_de",
        "entubamento_ate",
        "especialista_1",
        "horas_especialista_1",
        "especialista_2",
        "horas_especialista_2",
        "especialista_3",
        "horas_especialista_3",
        "especialista_4",
        "horas_especialista_4",
        "servente_1",
        "horas_servente_1",
        "servente_2",
        "horas_servente_2",
        "servente_3",
        "horas_servente_3",
        "servente_4",
        "horas_servente_4",
        "bit_novo",
        "bit_novo_de",
        "bit_novo_ate",
        "turno",
    ]

    for relatorio in RelatorioTurno.objects.all():
        try:
            registo = RegistoDiarioEmpregado.objects.get(pk=relatorio.registo_id)
        except RegistoDiarioEmpregado.DoesNotExist:
            continue

        campos_update = []
        for campo in campos_diretos:
            setattr(registo, campo, getattr(relatorio, campo))
            campos_update.append(campo)

        registo.relatorio_horas_paragem = relatorio.horas_paragem or "nao"
        campos_update.append("relatorio_horas_paragem")

        registo.save(update_fields=campos_update)


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0061_remove_relatorioturno_polimeros_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registodiarioempregado',
            name='avanco_turno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='avaria',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='avaria_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='avaria_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='bit_novo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='bit_novo_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='bit_novo_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='bomba_captacao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='bomba_injecao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='cimentacao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='cimentacao_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='cimentacao_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='diametro_furo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='entubamento',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='entubamento_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='entubamento_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='especialista_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='especialista_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='especialista_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='especialista_4',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='estaleiro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='furacao_avanco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='furacao_descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='furacao_fim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='furacao_inicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='furacao_recuperacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='furacao_rocha',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_especialista_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_especialista_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_especialista_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_especialista_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_paragem_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_paragem_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_servente_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_servente_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_servente_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='horas_servente_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='inclinacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='lavar_furo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='lavar_furo_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='lavar_furo_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='manobra',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='manobra_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='manobra_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='medicao_desvio',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='medicao_desvio_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='medicao_desvio_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='no_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='no_inicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='numero_relatorio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='numero_sondagem',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='outros',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='outros_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='outros_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='percentagem_recuperacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='polimeros',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='polimeros_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='polimeros_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='reaming',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='reaming_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='reaming_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='relatorio_horas_paragem',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='servente_1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='servente_2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='servente_3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='servente_4',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='sonda',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='testemunho_recuperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='torre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='turno',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='varas_presas',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='varas_presas_ate',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registodiarioempregado',
            name='varas_presas_de',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrar_relatorio_turno_para_registo, migrations.RunPython.noop),
    ]
