# Generated by Django 6.0.4 on 2026-05-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0062_registodiarioempregado_avanco_turno_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RelatorioTurno",
        ),
    ]
