# Generated by Django 6.0.4 on 2026-05-08

from django.db import migrations, models


def migrar_furacao_legado_para_lista(apps, schema_editor):
    RegistoDiarioEmpregado = apps.get_model("projetos", "RegistoDiarioEmpregado")
    for registo in RegistoDiarioEmpregado.objects.all():
        if registo.furacoes:
            continue
        valores = [
            registo.furacao_inicio,
            registo.furacao_fim,
            registo.furacao_avanco,
            registo.furacao_recuperacao,
            registo.furacao_rocha,
            registo.furacao_descricao,
        ]
        if all(valor in (None, "", []) for valor in valores):
            continue
        registo.furacoes = [
            {
                "inicio": float(registo.furacao_inicio) if registo.furacao_inicio is not None else None,
                "fim": float(registo.furacao_fim) if registo.furacao_fim is not None else None,
                "avanco": float(registo.furacao_avanco) if registo.furacao_avanco is not None else None,
                "recuperacao": float(registo.furacao_recuperacao) if registo.furacao_recuperacao is not None else None,
                "rocha": registo.furacao_rocha or "",
                "descricao": registo.furacao_descricao or "",
            }
        ]
        registo.save(update_fields=["furacoes"])


class Migration(migrations.Migration):

    dependencies = [
        ("projetos", "0063_delete_relatorioturno_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="registodiarioempregado",
            name="furacoes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrar_furacao_legado_para_lista, migrations.RunPython.noop),
    ]
