# Generated by Django 6.0.4 on 2026-05-08 20:31

from django.db import migrations, models


def _copiar_ocorrencias_legado(apps, schema_editor):
    RegistoDiarioEmpregado = apps.get_model("projetos", "RegistoDiarioEmpregado")

    for registo in RegistoDiarioEmpregado.objects.all().iterator():
        ocorrencias = []
        for tipo, campo_flag, campo_de, campo_ate in (
            ("manobra", "manobra", "manobra_de", "manobra_ate"),
            ("reaming", "reaming", "reaming_de", "reaming_ate"),
            ("avaria", "avaria", "avaria_de", "avaria_ate"),
            ("horas_paragem", "relatorio_horas_paragem", "horas_paragem_de", "horas_paragem_ate"),
            ("medicao_desvio", "medicao_desvio", "medicao_desvio_de", "medicao_desvio_ate"),
            ("cimentacao", "cimentacao", "cimentacao_de", "cimentacao_ate"),
            ("lavar_furo", "lavar_furo", "lavar_furo_de", "lavar_furo_ate"),
            ("varas_presas", "varas_presas", "varas_presas_de", "varas_presas_ate"),
            ("entubamento", "entubamento", "entubamento_de", "entubamento_ate"),
            ("bit_novo", "bit_novo", "bit_novo_de", "bit_novo_ate"),
            ("outros", "outros", "outros_de", "outros_ate"),
        ):
            valor_flag = getattr(registo, campo_flag, None)
            hora_de = getattr(registo, campo_de, None)
            hora_ate = getattr(registo, campo_ate, None)
            ativo = valor_flag == "sim" if campo_flag != "outros" else valor_flag not in (None, "")
            if not ativo and not hora_de and not hora_ate:
                continue
            ocorrencias.append(
                {
                    "tipo": tipo,
                    "de": hora_de.strftime("%H:%M") if hora_de else "",
                    "ate": hora_ate.strftime("%H:%M") if hora_ate else "",
                }
            )

        if ocorrencias:
            registo.operacoes_ocorrencias = ocorrencias
            registo.save(update_fields=["operacoes_ocorrencias"])


def _reverter_ocorrencias_legado(apps, schema_editor):
    RegistoDiarioEmpregado = apps.get_model("projetos", "RegistoDiarioEmpregado")
    RegistoDiarioEmpregado.objects.exclude(operacoes_ocorrencias=[]).update(operacoes_ocorrencias=[])


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0064_registodiarioempregado_furacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='registodiarioempregado',
            name='operacoes_ocorrencias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(_copiar_ocorrencias_legado, _reverter_ocorrencias_legado),
    ]
