# Generated by Django 6.0.4 on 2026-05-08 21:51

from django.db import migrations, models


def _copiar_equipa_legado(apps, schema_editor):
    RegistoDiarioEmpregado = apps.get_model("projetos", "RegistoDiarioEmpregado")

    for registo in RegistoDiarioEmpregado.objects.all().iterator():
        equipa = []
        for prefixo, rotulo in (("especialista", "Especialista"), ("servente", "Servente")):
            for index in range(1, 5):
                nome = getattr(registo, f"{prefixo}_{index}", "") or ""
                horas = getattr(registo, f"horas_{prefixo}_{index}", None)
                if not nome and horas in (None, ""):
                    continue
                equipa.append(
                    {
                        "funcao": rotulo,
                        "nome": str(nome).strip(),
                        "horas": float(horas) if horas not in (None, "") else None,
                    }
                )

        if equipa:
            registo.equipa_turno = equipa
            registo.save(update_fields=["equipa_turno"])


def _reverter_equipa_legado(apps, schema_editor):
    RegistoDiarioEmpregado = apps.get_model("projetos", "RegistoDiarioEmpregado")
    RegistoDiarioEmpregado.objects.exclude(equipa_turno=[]).update(equipa_turno=[])


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0065_registodiarioempregado_operacoes_ocorrencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='registodiarioempregado',
            name='equipa_turno',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(_copiar_equipa_legado, _reverter_equipa_legado),
    ]
