# Generated by Django 6.0.4 on 2026-05-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0066_registodiarioempregado_equipa_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregados',
            name='dias_ferias_anuais',
            field=models.PositiveSmallIntegerField(default=22),
        ),
    ]
