# Generated by Django 6.0.4 on 2026-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0067_empregados_dias_ferias_anuais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registodiarioempregado',
            name='diametro_furo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
