# Generated by Django 6.0.4 on 2026-05-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0068_alter_registodiarioempregado_diametro_furo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registodiarioempregado',
            name='bit_novo',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
