# Generated by Django 6.0.4 on 2026-06-13 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_empresa_compliance_score_config'),
        ('projetos', '0074_medida_morta_na_configuracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipas', to='plataforma.empresa')),
                ('membros', models.ManyToManyField(blank=True, related_name='equipas', to='projetos.empregados')),
            ],
            options={
                'verbose_name': 'Equipa',
                'verbose_name_plural': 'Equipas',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nome'), name='projetos_equipa_nome_unico_por_empresa')],
            },
        ),
    ]
