# Generated by Django 6.0.4 on 2026-06-24 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0018_empresa_compliance_score_config'),
        ('projetos', '0075_equipa'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo3dimplicit',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_3d_implicit', to='plataforma.empresa'),
        ),
        migrations.AddField(
            model_name='modelo3dimplicit',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_3d_implicit', to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='modelo3dwireframe',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_3d_wireframe', to='plataforma.empresa'),
        ),
        migrations.AddField(
            model_name='modelo3dwireframe',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelos_3d_wireframe', to='projetos.projeto'),
        ),
    ]
