from . import dashboard
from . import projetos
from . import furos
from . import empregados
from . import maquinas
from . import material
from . import medicoes
from . import configuracao_perfuracao
from . import historico_configuracao