from django.urls import path

from geologia import views


app_name = "geologia"

urlpatterns = [
    path("", views.geologia_hub, name="hub"),
    path("empregado/geologo/", views.geologia_geologo_dashboard, name="empregado_geologo_dashboard"),
    path("empregado/encarregado-obra/", views.geologia_encarregado_dashboard, name="empregado_encarregado_dashboard"),
    path("cartografia-oficial/", views.cartografia_oficial, name="cartografia_oficial"),
    path("mapa-cartografico/", views.mapa_cartografico, name="mapa_cartografico"),
    path("mapa-cartografico/fontes/", views.fontes_cartograficas_manage, name="fontes_cartograficas_manage"),
    path("mapa-cartografico/fontes/nova/", views.fonte_cartografica_create, name="fonte_cartografica_create"),
    path("mapa-cartografico/fontes/<uuid:pk>/editar/", views.fonte_cartografica_update, name="fonte_cartografica_update"),
    path("mapa-cartografico/fontes/<uuid:pk>/alternar/", views.fonte_cartografica_toggle, name="fonte_cartografica_toggle"),
    path("mapa-cartografico/fontes/<uuid:pk>/duplicar/", views.fonte_cartografica_duplicate, name="fonte_cartografica_duplicate"),
    path("mapa-cartografico/fontes/<uuid:pk>/apagar/", views.fonte_cartografica_delete, name="fonte_cartografica_delete"),
    path("drone/", views.drone_hub, name="drone_hub"),
    path("drone-sf/", views.drone_sf_hub, name="drone_sf_hub"),
    path("drone-sf/novo/", views.drone_sf_create, name="drone_sf_create"),
    path("drone-sf/demo/", views.drone_sf_demo_create, name="drone_sf_demo_create"),
    path("drone-sf/<uuid:pk>/", views.drone_sf_detail, name="drone_sf_detail"),
    path("drone-sf/<uuid:drone_id>/operacao/", views.drone_sf_operacao_detail, name="drone_sf_operacao_detail"),
    path("drone-sf/<uuid:drone_id>/comandos/novo/", views.drone_sf_comando_create, name="drone_sf_comando_create"),
    path("drone-sf/<uuid:drone_id>/missoes/<uuid:missao_id>/alternar/", views.drone_sf_missao_programada_toggle, name="drone_sf_missao_programada_toggle"),
    path("drone-sf/<uuid:drone_id>/missoes/<uuid:missao_id>/executar/", views.drone_sf_missao_programada_executar, name="drone_sf_missao_programada_executar"),
    path("drone-sf/<uuid:drone_id>/missoes/<uuid:missao_id>/apagar/", views.drone_sf_missao_programada_delete, name="drone_sf_missao_programada_delete"),
    path("drone-sf/<uuid:drone_id>/modulos/novo/", views.drone_sf_modulo_create, name="drone_sf_modulo_create"),
    path("drone-sf/<uuid:drone_id>/sensores/novo/", views.drone_sf_sensor_create, name="drone_sf_sensor_create"),
    path("drone-sf/api/bridge/ingest/", views.api_drone_sf_bridge_ingest_estado, name="api_drone_sf_bridge_ingest_estado"),
    path("drone-sf/api/bridge/log/", views.api_drone_sf_bridge_log_event, name="api_drone_sf_bridge_log_event"),
    path("drone-sf/api/bridge/comandos/", views.api_drone_sf_bridge_comandos_pendentes, name="api_drone_sf_bridge_comandos_pendentes"),
    path("drone-sf/api/bridge/comandos/<uuid:comando_id>/confirmar/", views.api_drone_sf_bridge_confirmar_comando, name="api_drone_sf_bridge_confirmar_comando"),
    path("drone-sf/<uuid:drone_id>/api/estado/", views.api_drone_sf_estado, name="api_drone_sf_estado"),
    path("drone/controlo/atualizar/", views.drone_controle_update, name="drone_controle_update"),
    path("drone/comandos/novo/", views.drone_comando_create, name="drone_comando_create"),
    path("drone/api/testar-ligacao/", views.api_testar_ligacao_drone, name="api_testar_ligacao_drone"),
    path("drone/api/procurar/", views.api_procurar_drone, name="api_procurar_drone"),
    path("drone/api/estado/", views.api_estado_drone, name="api_estado_drone"),
    path("drone/api/bridge/ingest/", views.api_bridge_ingest_estado, name="api_bridge_ingest_estado"),
    path("drone/api/bridge/log/", views.api_bridge_log_event, name="api_bridge_log_event"),
    path("drone/api/bridge/comandos/", views.api_bridge_comandos_pendentes, name="api_bridge_comandos_pendentes"),
    path("drone/api/bridge/comandos/<uuid:comando_id>/confirmar/", views.api_bridge_confirmar_comando, name="api_bridge_confirmar_comando"),
    path("furos/<uuid:furo_id>/", views.furo_geologia_dashboard, name="furo_dashboard"),
    path("furos/<uuid:furo_id>/logs/novo/", views.log_geologico_create, name="log_create"),
    path("logs/meus/", views.meus_logs_geologicos, name="meus_logs"),
    path("logs/planeamento-amostragem/", views.planeamento_amostragem_geologo, name="planeamento_amostragem"),
    path("logs/qualidade-dados/", views.qualidade_dados_geologo, name="qualidade_dados"),
    path("logs/correlacoes-geologia-perfuracao/", views.correlacoes_geologia_perfuracao, name="correlacoes_geologia_perfuracao"),
    path("logs/mapa-furos-2d-3d/", views.mapa_furos_2d_3d_geologo, name="mapa_furos_2d_3d"),
    path("logs/pendentes-validacao/", views.logs_pendentes_validacao, name="logs_pendentes_validacao"),
    path("logs/intervalos-conflito/", views.logs_intervalos_conflito, name="logs_intervalos_conflito"),
    path("logs/intervalos-conflito/resolver/", views.resolver_intervalo_conflito, name="resolver_intervalo_conflito"),
    path("logs/mapa-litologico/", views.mapa_litologico_furo, name="mapa_litologico_furo"),
    path("logs/alertas-geotecnicos/", views.alertas_geotecnicos, name="alertas_geotecnicos"),
    path("logs/relatorio/", views.relatorio_geologico, name="relatorio_geologico"),
    path("logs/relatorio/export/<str:formato>/", views.relatorio_geologico_export, name="relatorio_geologico_export"),
    path("logs/relatorio/executivo/print/", views.relatorio_geologico_executivo_print, name="relatorio_geologico_executivo_print"),
    path("logs/<uuid:pk>/", views.log_geologico_detail, name="log_detail"),
    path("logs/<uuid:pk>/editar/", views.log_geologico_update, name="log_update"),
    path("logs/<uuid:pk>/apagar/", views.log_geologico_delete, name="log_delete"),
    path("furos/<uuid:furo_id>/drone/nova/", views.missao_drone_create, name="missao_create"),
    path("drone/<uuid:pk>/", views.missao_drone_detail, name="missao_detail"),
    path("drone/<uuid:pk>/editar/", views.missao_drone_update, name="missao_update"),
    path("logs/<uuid:pk>/anexos/novo/", views.anexo_log_create, name="anexo_create"),
]
