from django.http import Http404


_AREAS_TODO = {
    "plataforma": {
        "nome": "Plataforma",
        "descricao": "Backoffice SaaS, subscrições, features, finanças e operações de administração global.",
        "feito": [
            "Dashboard de plataforma com métricas operacionais e atalhos rápidos.",
            "Gestão de planos/subscrições com fluxo de cobrança e configuração PayPal.",
            "Controlo de features por entidade (empresa/individual) com painel dedicado.",
            "Área de úteis para exportação/limpeza de dados de IA e tarefas técnicas.",
            "Arquivo técnico de furos terminado já disponível em `Úteis`, com detalhe de snapshot para consulta histórica por superuser.",
            "Dashboard TO DO com visão por app e detalhe de progresso já operacional para superuser.",
            "Revisão global dos templates com cobertura de tradução consolidada em toda a navegação principal.",
            "Nova camada de separação aplicada em `plataforma/views/empresas.py`: atualização de renovação e alteração de plano agora com processamento centralizado em `services/empresas.py`.",
            "Nova camada de separação aplicada em `plataforma/views/financas.py`: fluxos de checkout e retorno PayPal passaram a orquestração por service, com redução de lógica inline e padronização de mensagens por nível.",
            "Nova camada adicional em `plataforma/views/financas.py`: fluxos GET/POST de saída financeira e configuração PayPal unificados em builders (`processar_fluxo_saida_financeira` e `processar_fluxo_configuracao_paypal`) em `services/financas.py`.",
            "Nova camada de separação aplicada em `plataforma/views/planos.py`: create/update de plano unificados num builder (`processar_fluxo_form_plano`) em `services/planos.py`.",
            "Nova camada de separação aplicada em `plataforma/views/subscricoes.py`: construção de contexto da listagem movida para `services/subscricoes.py` (`construir_contexto_subscricao_list`).",
        ],
        "proximos_passos": [
            "Consolidar mais regras em services/selectors para reduzir lógica residual nas views de backoffice.",
            "Fechar ciclo de auditoria de permissões por tipo de conta com cenários automatizados.",
            "Expandir cobertura de internacionalização em mensagens de backend e validações de formulários.",
            "Extrair contextos de detalhe/edição de empresa para services de página e reduzir placeholders de métricas.",
            "Uniformizar ainda mais os fluxos financeiros (entrada/saída/config/paypal) com builders de contexto dedicados por página.",
        ],
        "falta_fazer": [
            "API versionada para operações administrativas críticas.",
            "Testes end-to-end de onboarding/subscrição/pagamento.",
        ],
        "estado_logica": "Boa evolução: separação forte em selectors/services (incluindo empresas e fluxos PayPal em finanças), com pendências pontuais de consolidação.",
    },
    "dispositivos": {
        "nome": "Dispositivos",
        "descricao": "Integração e monitorização de equipamentos e telemetria operacional.",
        "feito": [
            "Dashboard e navegação principal de dispositivos disponível na plataforma.",
            "Estruturas para registo/consulta de leituras e integração operacional já em produção.",
            "Primeira camada de separação aplicada em `dispositivos/views.py`: criação de sessão de captura e registo de dispositivo detectado delegados para services.",
            "Segunda camada aplicada: APIs de escuta e inspeção Bluetooth/USB delegadas para services com validação centralizada.",
            "Terceira camada aplicada: teste de leitura USB (`api_testar_leitura_usb`) movido para service com orquestração de eventos.",
            "Refatoração estrutural concluída: `dispositivos/services/dashboard.py` passou a fachada e a implementação foi dividida em `dashboard_registry`, `dashboard_capture` e `dashboard_discovery`.",
            "Revisão curta final: procura Bluetooth também movida para service e validações duplicadas removidas das views.",
            "Conector inicial MagCruiser implementado com importação por ficheiro (`CSV/LAS`) e pré-visualização antes de gravar.",
            "Deteção de nome de furo nas medições importadas (ex.: `hole`, `hole_name`, `furo`) com mapeamento automático para furos da empresa.",
            "Modos de aplicação da importação entregues: todas as medições, apenas última por furo, e criação automática de furos em falta.",
            "Relatório de importação já operacional com totais (gravadas/ignoradas/criadas), detalhe por furo e opção de descarregar CSV.",
            "Histórico de importações por empresa guardado em base de dados, visível na página de captura.",
            "Proteção de fallback aplicada na captura para evitar erro 500 quando a tabela de histórico ainda não existe no ambiente.",
            "Nova camada aplicada em `dispositivos/views.py`: fluxo POST da página de captura movido para `services/captura_page.py` (importação e criação de sessão).",
            "Nova camada aplicada: padronização de respostas API com `services/api_flow.py`, reduzindo duplicação em endpoints Bluetooth/USB.",
            "Nova camada aplicada: contextos de dashboard/listagens/detalhes movidos para `services/dashboard_page.py`, com views mais finas.",
            "Nova camada aplicada: captura serial de sessão (`capturar_leitura_serial_view`) extraída para service dedicado de orquestração.",
            "Nova camada adicional em `dispositivos/views.py`: respostas HTTP de endpoints API Bluetooth/USB padronizadas via helper único (`construir_http_response_operacao_api`) no `services/api_flow.py`.",
        ],
        "proximos_passos": [
            "Completar uniformização dos endpoints API restantes para usar o mesmo padrão de resposta/orquestração.",
            "Adicionar validações de consistência para entradas de telemetria em lote.",
            "Adicionar importação dedicada para `XLSX` mantendo o mesmo fluxo (preview -> validação -> gravação).",
            "Melhorar reconciliação automática de nomes de furo com regras de normalização/fuzzy matching configurável por empresa.",
            "Concluir rollout operacional da migração `dispositivos.0006_importacaodispositivohistorico` em todos os ambientes (local e servidor).",
        ],
        "falta_fazer": [
            "API pública para ingestão externa com autenticação forte e versionamento.",
            "Observabilidade detalhada por dispositivo (latência, erro, disponibilidade).",
        ],
        "estado_logica": "Boa evolução e já bastante madura: fluxo MagCruiser funcional, histórico ativo e views principais de Dispositivos mais leves após extração de API flow, contexto de páginas e captura serial; pendências focadas em expansão de formatos e API externa.",
    },
    "projetos": {
        "nome": "Projetos",
        "descricao": "Gestão principal do negócio: projetos, furos, registos, materiais, medições e equipa.",
        "feito": [
            "Fluxos completos para projetos/furos/medições/materiais e operações de campo.",
            "Várias rotas já migradas para services/selectors (empregados, stock, acesso contextual, sugestões).",
            "Suporte a contas individual e empregado com regras específicas de acesso.",
            "Refatorações de UI/UX em páginas de furo 3D e detalhe, incluindo melhorias mobile.",
            "Fluxo de avarias de máquinas com atribuição de responsável, atualização por responsável e notificações por email para envolvidos.",
            "Lista de despesas da empresa evoluída com ações por registo (ver, editar e apagar), incluindo detalhe e confirmação de remoção.",
            "Formulário de despesa atualizado com botão de voltar sem gravar.",
            "Nova camada de separação aplicada em `views/materiais.py`: fluxos de criação/edição e movimentos (levantamento/devolução) consolidados com helpers de orquestração.",
            "Nova camada adicional em `views/materiais.py`: fluxos de entrada/saída de stock e pipeline de formulário create/update passaram a builders em `services/stock.py`, reduzindo repetição na view.",
            "Nova camada adicional em `views/materiais.py`: fluxo GET/POST de levantamento/devolução (initial + bind + submissão) movido para `processar_fluxo_movimento_material_form` em `services/stock.py`.",
            "Nova camada de separação aplicada em `views/despesas.py`: resolução de contexto (admin/individual) e submissão de formulários centralizadas.",
            "Nova camada adicional em `views/despesas.py`: update e delete administrativo agora também orquestrados por service (`processar_submissao_form_despesa_update` e `processar_acao_apagar_despesa`).",
            "Nova camada adicional em `views/despesas.py`: fluxos GET/POST de create/update (admin/individual) unificados em builder (`processar_fluxo_form_despesa`) no `services/despesas.py`.",
            "Nova camada de separação aplicada em `views/registos.py`: submissões de create/update (empregado/admin) e renderização de formulário padronizadas.",
            "Nova camada adicional em `views/registos.py`: fluxos POST/GET de formulário (empregado e admin) extraídos para builders em `services/registos.py`, reduzindo duplicação nas views.",
            "Nova camada de separação aplicada em `views/configuracao_perfuracao.py`: tratamento de `ValidationError` e pipeline create/update (admin/empregado) unificados.",
            "Nova camada adicional em `views/configuracao_perfuracao.py`: fluxos GET/POST de create/update (admin/empregado) movidos para builder em `services/configuracao_perfuracao.py` (`processar_fluxo_form_configuracao_perfuracao`).",
            "Nova camada de separação aplicada em `views/medicoes.py`: render de formulário padronizado e redução de repetição nos fluxos create/update.",
            "Nova camada de separação aplicada em `views/projetos.py`: helpers para `empresa_id`, fluxo de formulário create/update e simplificação de associação de empregado.",
            "Nova camada de separação aplicada em `views/empregados.py`: fluxos de formulário create/update de empregado e adicionar/editar ligação de projeto centralizados em builders de `services/empregados.py`.",
            "Nova camada adicional em `views/empregados.py`: fluxo GET/POST de adição de ficheiro ao empregado centralizado em `processar_fluxo_ficheiro_empregado_admin_form` no service.",
            "Nova camada de separação aplicada em `views/empregado_area.py`: renderização de formulários de edição (individual/empregado) padronizada.",
            "Nova camada adicional em `views/empregado_area.py`: fluxos GET/POST de edição de dados (individual e empregado) extraídos para builders em `services/empregado_area.py`.",
            "Nova camada de separação aplicada em `views/opcoes.py`: resolução de contexto admin e submissão de preferências/definições financeiras centralizadas.",
            "Nova camada adicional em `views/opcoes.py`: fluxos GET/POST de preferências e definições financeiras consolidados em builders no `services/opcoes.py`.",
            "Nova camada de separação aplicada em `views/maquina_avarias.py`: criação de avarias (admin/empregado) unificada com helpers de orquestração.",
            "Nova camada adicional em `views/maquina_avarias.py`: fluxos GET/POST de create/update de avarias migrados para builders em `services/maquina_avarias.py`.",
            "Nova camada de separação aplicada em `views/definicoes.py`: processamento de preferências e ativação de idioma encapsulados em helpers dedicados.",
            "Nova camada adicional em `views/definicoes.py`: fluxo GET/POST do formulário de preferências movido para builder em `services/definicoes.py`.",
            "Nova camada de separação aplicada em `views/maquinas.py`: criação/edição com pipeline de formulário unificado e renderização de formulário padronizada.",
            "Nova camada adicional em `views/maquinas.py`: fluxo create/update delegado para `processar_fluxo_form_maquina` em service, reduzindo duplicação de orquestração HTTP.",
            "Nova camada de separação aplicada em `views/empregado_furo.py`: preparação/renderização de formulário de ligação trabalhador-furo extraídas para helpers reutilizáveis.",
            "Tradução i18n avançada em múltiplos templates operacionais e dashboards.",
            "Revisão final de tradução nos principais templates de detalhe, listagens, exportação e dashboards.",
            "Nova camada de separação em furos concluída: contexto de detalhe, resolução de acesso 3D, fluxos create/list/update, delete e importação 3D externa movidos para services.",
            "Nova camada adicional em `views/furos.py`: orquestração GET/POST de create/update consolidada em builders (`processar_fluxo_form_furo_create`/`processar_fluxo_form_furo_update`) no `services/furo_fluxos.py`.",
            "Lógica pesada do gráfico 3D de furos extraída para service dedicado (`furo_3d_chart`), reduzindo significativamente a complexidade da view.",
            "Uniformização visual em curso: várias páginas críticas já migradas para paleta de botões consistente e menos saturada.",
            "3D avançado evoluído com exportação técnica no Implicit Model (CSV da seleção + JSON técnico com pontos filtrados, resumo por domínio e metadados de filtros).",
            "3D avançado evoluído com camada analítica inicial no Implicit Model (extensões X/Y/Z, volume envolvente e estimativa por domínio litológico).",
            "3D avançado evoluído com exportação técnica no Block Model (CSV da seleção + JSON técnico com resumo e filtros ativos).",
            "Paridade de persistência de configuração concluída entre Block Model e Implicit Model: reabertura fiel por modelo com sincronização para `resumo_json` em backend.",
            "Estado da fase 3D avançado registado: núcleo funcional concluído em Wireframe, Block e Implicit (upload, preview, filtros, animações, exportação técnica e persistência de configuração).",
            "Implicit Model evoluído com slice planes interativos (eixo X/Y/Z + posição + plano visual + contagem de pontos visíveis) sem reset de câmara.",
            "Implicit Model evoluído com preenchimento geológico por domínio via zonas extrudidas e controlo de espessura da zona.",
            "Extrusão geológica evoluída para modo unidirecional com heurística por `solo` e override manual (`auto`, `forçar para baixo`, `forçar para cima`).",
            "Implicit Model evoluído com interpolação/suavização configurável (níveis 1-3) para superfícies mais contínuas.",
            "Iso-linhas no Implicit Model entregues com plano selecionável (X/Y/Z), número de níveis, intensidade visual e modo alto contraste (neon).",
            "Legenda técnica das iso-linhas entregue (por domínio, eixo, faixa numérica e níveis), incluindo marcação por cor do domínio.",
            "Navegação técnica do gráfico evoluída com ações `Focar seleção` e `Limpar foco` para recentrar rapidamente análise filtrada.",
            "Comparação temporal A/B no Implicit Model entregue com overlay de modelo B, resumo de diferenças por domínio e persistência de estado de UI.",
            "Delta espacial A/B entregue no Implicit Model com marcadores de ganho/perda (+/-), casca volumétrica opcional e controlos dedicados de opacidade/tamanho.",
            "Presets de visualização técnica por perfil entregues no Implicit Model (Operacional, Geologia, Supervisão).",
        ],
        "proximos_passos": [
            "Continuar migração de lógica restante de views para camadas dedicadas, com foco em módulos ainda densos de operação e registos técnicos.",
            "Unificar validações de domínio críticas (ex.: regras de inclinação por tipo de furo).",
            "Reforçar testes de regressão para permissões entre superuser/admin/empregado/individual.",
            "Fechar i18n residual em mensagens transversais e textos técnicos específicos.",
            "Aplicar o mesmo padrão de orquestração por fluxos nas views restantes de operações e registos técnicos.",
            "Concluir varredura visual final para remover estilos legacy com cores vivas remanescentes em templates menos usados.",
            "Plano 3D avançado (1/10): normalizar ingestão de dados 3D (OBJ/CSV/JSON/LAS), com validação robusta e mensagens de erro claras.",
            "Plano 3D avançado (2/10): consolidar o pipeline de geometria em pontos 3D normalizados (X, Y, Z), preservando metadados por domínio litológico.",
            "Plano 3D avançado (3/10): reforçar modelo Wireframe com controlo de camadas e estados visuais persistentes por utilizador.",
            "Plano 3D avançado (4/10): evoluir Block Model para voxels configuráveis (resolução/tamanho), com filtros por intervalos e domínio.",
            "Plano 3D avançado (5/10): amadurecer Implicit Model com modos Delaunay/Convex Hull estáveis, alternância por checkbox e sem reset de câmara.",
            "Plano 3D avançado (6/10): adicionar animações opcionais por checkbox (rotação, pulso, relevo/terreno), mantendo a pose atual da câmara.",
            "Plano 3D avançado (7/10): enriquecer paleta geológica com mapeamento padrão por rocha (granito, quartzo, xisto, pirite, minério, argila, jaspe e variantes).",
            "Plano 3D avançado (8/10): concluído para Block/Implicit no estado atual (configuração visual persistida em `resumo_json` + reabertura fiel por modelo).",
            "Plano 3D avançado (9/10): concluído para Block/Implicit no estado atual (exportação técnica CSV/JSON com seleção ativa e metadados).",
            "Plano 3D avançado (10/10): concluído em fase inicial (métricas rápidas e volumetria envolvente; próximo passo: cortes e comparação temporal).",
            "[Curto prazo] Roadmap de equiparação (1/8): evoluir motor geológico para modelação implícita avançada com interpolação robusta, constraints, faults e domaining assistido.",
            "[Curto prazo] Roadmap de equiparação (4/8): reforçar performance para grande escala (milhões de pontos/blocos, renderização e consultas otimizadas).",
            "[Curto prazo] Roadmap de equiparação (5/8): expandir integrações industriais (DXF/DWG/LAS/APIs) e sincronização com ERPs/sensores/equipamentos.",
            "[Médio prazo] Roadmap de equiparação (2/8): adicionar camada completa de planeamento mineiro (design, fases, sequenciamento e comparação de cenários).",
            "[Médio prazo] Roadmap de equiparação (6/8): reforçar governança e compliance (auditoria, versionamento técnico, permissões granulares e aprovação por workflow).",
            "[Médio prazo] Roadmap de equiparação (7/8): aumentar automação inteligente (alertas preditivos, recomendações operacionais e assistente técnico contextual).",
            "[Longo prazo] Roadmap de equiparação (3/8): implementar geoestatística e estimativas (variografia, kriging, classificação de recursos/reservas e auditoria técnica).",
            "[Longo prazo] Roadmap de equiparação (8/8): consolidar camada enterprise (testes de carga, documentação técnica, suporte e onboarding em escala).",
            "[Próxima fase 3D] Evoluir métricas volumétricas para além de bounding box (estimativa por malha/superfície e por domínio).",
            "[Próxima fase 3D] Aplicar otimizações finais de performance para datasets de maior escala (render e filtros em tempo real).",
            "[Próxima fase 3D] Adicionar comparação lado-a-lado entre modelos (A/B) com sincronização de câmara e diferenças por domínio.",
        ],
        "falta_fazer": [
            "API versionada para mobile/sensores/drones com contratos estáveis.",
            "Histórico temporal completo de evolução de furo com consultas otimizadas.",
        ],
        "estado_logica": "Boa e em aceleração: além do núcleo de furos, também materiais, despesas (incluindo update/delete), registos, configuração de perfuração, medições, projetos/opções, definições e avarias já receberam nova camada de separação; no 3D avançado, Block/Implicit já contam com persistência backend, exportação técnica, cortes, iso-linhas avançadas, extrusão geológica, presets por perfil, comparação temporal A/B e controlo de foco, restando agora sobretudo volumetria mais precisa e otimização para escala.",
    },
    "ia": {
        "nome": "IA",
        "descricao": "AI Visual, chatbox operacional, memória de trabalho e biblioteca documental.",
        "feito": [
            "Hub IA, chatbox, memória operacional e histórico de análises disponíveis.",
            "Suporte a biblioteca de documentos para contexto operacional da IA.",
            "Exportação/limpeza de datasets IA disponível na área de úteis (superuser).",
            "Melhorias na experiência do chatbox e base para fluxos de respostas guiadas clicáveis.",
        ],
        "proximos_passos": [
            "Aumentar qualidade de OCR e pipelines por zona configurável.",
            "Consolidar leitura multimodal e pós-processamento semântico por domínio.",
            "Estruturar serviços de resposta guiada com sugestões clicáveis em mais cenários.",
        ],
        "falta_fazer": [
            "RAG/API versionada com controles de permissão por empresa/projeto.",
            "Métricas de qualidade por tipo de documento e feedback loop contínuo.",
        ],
        "estado_logica": "Intermédio: núcleo funcional em produção, com refatoração contínua para serviços especializados.",
    },
    "geologia": {
        "nome": "Geologia",
        "descricao": "Operação geológica, integração drone e suporte técnico de terreno.",
        "feito": [
            "Hub geologia e interfaces de drone integrados no ecossistema principal.",
            "Refatorações recentes já moveram partes de submissão para services dedicados.",
            "Tradução i18n reforçada em páginas principais de missão/log e dashboard de furo geológico.",
            "Fluxos de logs geológicos (create/update/anexo) agora orquestrados em service dedicado, com views mais leves.",
            "Nova camada adicional em `geologia/views/logs.py`: fluxos GET/POST de create/update/anexo unificados em builders no `services/logs.py` (`processar_fluxo_*`).",
            "Fluxos de drone (comandos, importação de missão e missão create/update) extraídos para service, reduzindo lógica inline nas views.",
            "Camada Drone S_F também evoluída: criação de comando passou a usar builders/processadores em service (`drone_sf_dashboard`).",
            "APIs bridge do Drone S_F (ingest/comandos/confirmar/log) agora usam resolução comum de autorização em service, removendo repetição nas views.",
            "Ações de missão programada S_F (toggle/executar/remover) extraídas para service, deixando `dashboard.py` mais focado em HTTP/UI.",
            "Nova camada de separação aplicada em `geologia/views/drone.py`: validação de empresa necessária e pipeline de formulário de missão (create/update) consolidados em helpers.",
            "Nova camada de separação aplicada em `geologia/views/dashboard.py`: tratamento de ações POST do detalhe de operação e criação de comando S_F centralizados em helpers.",
            "Nova camada de separação aplicada em `geologia/views/dashboard.py`: fluxos POST do detalhe de operação S_F e criação de comando movidos para `services/drone_sf_page.py`, reduzindo lógica de orquestração na view.",
            "Nova camada aplicada nos endpoints bridge S_F: resolução de contexto (autorização + operação + payload JSON) unificada em helper de service (`resolver_contexto_bridge_sf`), reduzindo duplicação nas APIs de ingest/comandos/confirmação/log.",
            "Nova camada de separação aplicada em `geologia/views/drone.py`: fluxo create/update de missão consolidado em builder `processar_fluxo_form_missao` no service, reduzindo lógica repetida de POST/GET.",
            "Nova camada adicional em `geologia/views/drone.py`: fluxo de importação de missão DJI no hub consolidado em `processar_fluxo_importacao_missao` no service.",
            "Nova camada adicional em `geologia/views/drone.py`: fluxos de atualização do controlo e criação de comando movidos para builders em `services/drone_dashboard.py`.",
            "Nova camada adicional em `geologia/views/dashboard.py`: ações de missão programada S_F (toggle/executar/remover) unificadas em helper único de service (`processar_acao_missao_programada_sf`).",
        ],
        "proximos_passos": [
            "Migrar restantes ações de escrita e importação para services/selectors.",
            "Padronizar validações de missão e trilhas de auditoria operacionais.",
            "Continuar a refatoração dos endpoints bridge para manter padrão único de resposta/orquestração em API.",
            "[NOVA FASE] Evoluir Geologia para nível profissional com duas entregas principais: `Block Model 3D profissional` e `Implicit Model 3D simplificado`.",
            "[NOVA FASE · Block Model] Evoluir os modelos já existentes (`Modelo3DBlock`) com esquema profissional incremental, criando `BlockModelCell` e mantendo compatibilidade com dados atuais.",
            "[NOVA FASE · Block Model] Implementar services: `gerar_block_model_para_projeto`, `calcular_blocos_a_partir_das_medicoes`, `atribuir_litologia_ao_bloco`, `exportar_block_model_json`.",
            "[NOVA FASE · Block Model] Implementar selectors: `obter_block_models_projeto`, `obter_celulas_block_model`, `obter_dados_3d_block_model` com foco em queries eficientes para PostgreSQL.",
            "[NOVA FASE · Block Model] Reforçar as views/templates já existentes (`modelo_3d_block_model` e hub 3D) com fluxo profissional progressivo: list/create/detail/3d/delete, filtros por litologia/profundidade, toggle de furos e opção 'só blocos com dados'.",
            "[NOVA FASE · Block Model] Entregar resumo técnico na página 3D: total de blocos, volume estimado e litologias encontradas.",
            "[NOVA FASE · Implicit] Após Block Model, evoluir o `Modelo3DImplicit` atual para esquema profissional com `ImplicitModelSurface`, método de interpolação configurável e malha/pontos persistidos.",
            "[NOVA FASE · Implicit] Implementar services: `gerar_implicit_model_para_projeto`, `obter_pontos_geologicos_do_projeto`, `interpolar_superficie_litologia`, `gerar_malha_superficie`, `exportar_implicit_model_json`.",
            "[NOVA FASE · Implicit] Reforçar selectors e as páginas atuais de Implicit para visualização profissional de superfícies/zonas interpoladas + comparação com furos reais, sem ruptura de UX existente.",
            "[NOVA FASE · Arquitetura] Garantir padrão limpo com `services/`, `selectors/`, URLs em `url_patterns/`, mensagens, logger `core`, permissões (`@login_required`, `@admin_required`) e zero lógica pesada em views.",
            "[NOVA FASE · Segurança/Dados] Reforçar isolamento multiempresa para nunca expor dados entre empresas e adicionar testes de regressão para permissões e consulta.",
        ],
        "falta_fazer": [
            "API de operações em tempo real com autenticação por dispositivo/operador.",
            "Pipeline de dados espaciais para analytics preditivo.",
            "Motor geológico avançado com block model persistente por célula e implicit model interpolado por litologia pronto para uso operacional.",
        ],
        "estado_logica": "Intermédio/boa e a subir: evolução consistente com redução forte de duplicação em logs/drone/dashboard e bridge. Nova fase aberta para Geologia 3D profissional (Block Model + Implicit) com implementação incremental iniciando por Block Model.",
    },
    "website": {
        "nome": "Website",
        "descricao": "Site público, páginas de entrada e jornada comercial/branding.",
        "feito": [
            "Homepage e estrutura pública funcional em produção.",
            "Ajustes recentes de conteúdo e posicionamento de funcionalidades principais.",
            "Páginas públicas principais já com uso consistente de tags de tradução.",
            "Revisão de consistência i18n na jornada pública (home, planos, login e registo).",
        ],
        "proximos_passos": [
            "Refinar copy comercial por idioma (tom e clareza), mantendo consistência com o produto.",
            "Melhorar prova social, métricas e CTA para conversão.",
        ],
        "falta_fazer": [
            "Funil de aquisição com tracking mais profundo e eventos padronizados.",
            "Páginas técnicas/documentação pública por módulo.",
        ],
        "estado_logica": "Boa para a fase atual, com foco em conteúdo, conversão e internacionalização completa.",
    },
    "infra_devops": {
        "nome": "Infra / Deploy",
        "descricao": "Operação de servidor, deploy contínuo, logs, observabilidade e rotinas de produção.",
        "feito": [
            "Deploy com Gunicorn + Nginx estabilizado e site em produção com HTTPS ativo.",
            "Pipeline operacional manual documentado (git pull, migrate, collectstatic, restart services).",
            "Ajustes de `ALLOWED_HOSTS`, cookies seguros e configuração de ambiente já aplicados em produção.",
            "Sitemap e robots já adicionados para indexação e SEO técnico.",
        ],
        "proximos_passos": [
            "Padronizar script único de deploy (pré-check, migrate, collectstatic, healthcheck e rollback).",
            "Adicionar healthcheck automático pós-deploy (`curl` rotas críticas + validação de login).",
            "Separar logs por serviço/módulo com rotação automática (`logrotate`) e retenção definida.",
            "Configurar alertas de disponibilidade e erros 5xx (email/Slack) com limiares claros.",
            "Automatizar backup de base de dados e media com testes periódicos de restore.",
        ],
        "falta_fazer": [
            "CI/CD com ambiente de staging espelho da produção.",
            "Runbooks de incidente e disaster recovery com RTO/RPO definidos.",
        ],
        "estado_logica": "Intermédio: produção funcional, mas ainda dependente de execução manual e com observabilidade parcial.",
    },
    "seguranca_qualidade": {
        "nome": "Segurança / Qualidade",
        "descricao": "Hardening de aplicação, cobertura de testes, auditoria de permissões e estabilidade funcional.",
        "feito": [
            "Checks de deploy já incorporados no fluxo operacional.",
            "Validações de domínio críticas já iniciadas (ex.: regras de inclinação por tipo de furo).",
            "Permissões por perfil (superuser/admin/empregado/individual) já estruturadas em múltiplos fluxos.",
        ],
        "proximos_passos": [
            "Completar matriz de permissões com testes automatizados por endpoint e por perfil.",
            "Adicionar testes de regressão para fluxos críticos (registo, login, furos, medições, despesas, avarias).",
            "Reforçar proteção de segredos/configuração sensível e revisão de variáveis de ambiente por ambiente.",
            "Executar varredura de segurança em dependências e corrigir CVEs com política de atualização.",
            "Criar bateria de smoke tests para validação rápida após cada release.",
        ],
        "falta_fazer": [
            "Suite E2E completa para jornadas críticas multi-perfil.",
            "Política de versionamento de API com testes de compatibilidade.",
        ],
        "estado_logica": "Boa base com avanços consistentes, mas ainda falta fechar automação de testes e hardening contínuo.",
    },
    "produto_comercial": {
        "nome": "Produto / Comercial",
        "descricao": "Experiência do utilizador, planos/subscrição, onboarding e preparação para escala de clientes.",
        "feito": [
            "Planos e subscrições funcionais com suporte a plano gratuito (valor zero).",
            "Configuração de pagamentos PayPal integrada na plataforma.",
            "Página de sugestões e canais de feedback já disponíveis para utilizadores.",
            "Menu e navegação por perfil bastante evoluídos (empresa, empregado, individual e superuser).",
        ],
        "proximos_passos": [
            "Concluir fluxo robusto de verificação de email e monitorização de entregabilidade SMTP.",
            "Melhorar onboarding guiado por tipo de conta (empresa vs individual) com checklist inicial.",
            "Criar dashboard comercial com métricas de ativação, retenção e conversão por plano.",
            "Definir versão trial/prova com limites de features e mensagens in-app claras.",
            "Refinar UX mobile em páginas operacionais com maior densidade de informação.",
        ],
        "falta_fazer": [
            "Funil completo de aquisição e retenção com eventos de produto padronizados.",
            "Playbook de suporte ao cliente e documentação de onboarding por segmento.",
        ],
        "estado_logica": "Intermédio/alto: núcleo comercial funcional, com foco agora em maturidade de onboarding, métricas e escala.",
    },
}


def listar_todo_areas():
    return [{"slug": slug, **dados} for slug, dados in _AREAS_TODO.items()]


def obter_todo_area(slug):
    try:
        return {"slug": slug, **_AREAS_TODO[slug]}
    except KeyError as exc:
        raise Http404("Área TO DO não encontrada.") from exc


def obter_notas_transversais_todo():
    return {
        "selectors_services": (
            "Estamos a retirar lógica solta para selectors/services em todas as apps. "
            "A base já está bem estruturada e houve avanço forte em Projetos (agora também materiais, registos, configuração de perfuração e medições), Furos/Despesas/Avarias e também em Dispositivos (importação MagCruiser com histórico, API flow padronizado e contexto de páginas extraído para services), mas a migração ainda está em curso nas camadas residuais de views/forms/helpers. "
            "No curto prazo, a prioridade operacional em Dispositivos é garantir a migração `0006_importacaodispositivohistorico` aplicada em todos os ambientes para eliminar dependência de fallback."
        ),
        "traducao": (
            "Estado atual de tradução: revisão ampla concluída nos templates visíveis do utilizador, incluindo Projetos, IA, Geologia, Plataforma e Website. "
            "Pontos pendentes concentram-se sobretudo em mensagens de backend/validação e alguns textos técnicos internos, não no menu principal."
        ),
        "governanca_execucao": (
            "As páginas TO DO foram expandidas para cobertura global ('para tudo'): apps funcionais + frentes transversais de Infra/Deploy, Segurança/Qualidade e Produto/Comercial. "
            "A recomendação é executar por ciclos curtos (1-2 semanas), com objetivos mensuráveis por área e revisão no fim de cada release."
        ),
    }
