from django.http import Http404


_AREAS_TODO = {
    "plataforma": {
        "nome": "Plataforma",
        "descricao": "Backoffice SaaS, subscrições, features, finanças e operações de administração global.",
        "feito": [
            "Dashboard de plataforma com métricas operacionais e atalhos rápidos.",
            "Gestão de planos/subscrições com fluxo de cobrança e configuração PayPal.",
            "Controlo de features por entidade (empresa/individual) com painel dedicado.",
            "Área de úteis para exportação/limpeza de dados de IA e tarefas técnicas.",
            "Arquivo técnico de furos terminado já disponível em `Úteis`, com detalhe de snapshot para consulta histórica por superuser.",
            "Dashboard TO DO com visão por app e detalhe de progresso já operacional para superuser.",
            "Revisão global dos templates com cobertura de tradução consolidada em toda a navegação principal.",
            "Nova camada de separação aplicada em `plataforma/views/empresas.py`: atualização de renovação e alteração de plano agora com processamento centralizado em `services/empresas.py`.",
            "Nova camada de separação aplicada em `plataforma/views/financas.py`: fluxos de checkout e retorno PayPal passaram a orquestração por service, com redução de lógica inline e padronização de mensagens por nível.",
            "Nova camada adicional em `plataforma/views/financas.py`: fluxos GET/POST de saída financeira e configuração PayPal unificados em builders (`processar_fluxo_saida_financeira` e `processar_fluxo_configuracao_paypal`) em `services/financas.py`.",
            "Nova camada de separação aplicada em `plataforma/views/planos.py`: create/update de plano unificados num builder (`processar_fluxo_form_plano`) em `services/planos.py`.",
            "Nova camada de separação aplicada em `plataforma/views/subscricoes.py`: construção de contexto da listagem movida para `services/subscricoes.py` (`construir_contexto_subscricao_list`).",
        ],
        "proximos_passos": [
            "Consolidar mais regras em services/selectors para reduzir lógica residual nas views de backoffice.",
            "Fechar ciclo de auditoria de permissões por tipo de conta com cenários automatizados.",
            "Expandir cobertura de internacionalização em mensagens de backend e validações de formulários.",
            "Extrair contextos de detalhe/edição de empresa para services de página e reduzir placeholders de métricas.",
            "Uniformizar ainda mais os fluxos financeiros (entrada/saída/config/paypal) com builders de contexto dedicados por página.",
        ],
        "falta_fazer": [
            "API versionada para operações administrativas críticas.",
            "Testes end-to-end de onboarding/subscrição/pagamento.",
        ],
        "estado_logica": "Boa evolução: separação forte em selectors/services (incluindo empresas e fluxos PayPal em finanças), com pendências pontuais de consolidação.",
    },
    "dispositivos": {
        "nome": "Dispositivos",
        "descricao": "Integração e monitorização de equipamentos e telemetria operacional.",
        "feito": [
            "Dashboard e navegação principal de dispositivos disponível na plataforma.",
            "Estruturas para registo/consulta de leituras e integração operacional já em produção.",
            "Primeira camada de separação aplicada em `dispositivos/views.py`: criação de sessão de captura e registo de dispositivo detectado delegados para services.",
            "Segunda camada aplicada: APIs de escuta e inspeção Bluetooth/USB delegadas para services com validação centralizada.",
            "Terceira camada aplicada: teste de leitura USB (`api_testar_leitura_usb`) movido para service com orquestração de eventos.",
            "Refatoração estrutural concluída: `dispositivos/services/dashboard.py` passou a fachada e a implementação foi dividida em `dashboard_registry`, `dashboard_capture` e `dashboard_discovery`.",
            "Revisão curta final: procura Bluetooth também movida para service e validações duplicadas removidas das views.",
            "Conector inicial MagCruiser implementado com importação por ficheiro (`CSV/LAS`) e pré-visualização antes de gravar.",
            "Deteção de nome de furo nas medições importadas (ex.: `hole`, `hole_name`, `furo`) com mapeamento automático para furos da empresa.",
            "Modos de aplicação da importação entregues: todas as medições, apenas última por furo, e criação automática de furos em falta.",
            "Relatório de importação já operacional com totais (gravadas/ignoradas/criadas), detalhe por furo e opção de descarregar CSV.",
            "Histórico de importações por empresa guardado em base de dados, visível na página de captura.",
            "Proteção de fallback aplicada na captura para evitar erro 500 quando a tabela de histórico ainda não existe no ambiente.",
            "Nova camada aplicada em `dispositivos/views.py`: fluxo POST da página de captura movido para `services/captura_page.py` (importação e criação de sessão).",
            "Nova camada aplicada: padronização de respostas API com `services/api_flow.py`, reduzindo duplicação em endpoints Bluetooth/USB.",
            "Nova camada aplicada: contextos de dashboard/listagens/detalhes movidos para `services/dashboard_page.py`, com views mais finas.",
            "Nova camada aplicada: captura serial de sessão (`capturar_leitura_serial_view`) extraída para service dedicado de orquestração.",
            "Nova camada adicional em `dispositivos/views.py`: respostas HTTP de endpoints API Bluetooth/USB padronizadas via helper único (`construir_http_response_operacao_api`) no `services/api_flow.py`.",
        ],
        "proximos_passos": [
            "Completar uniformização dos endpoints API restantes para usar o mesmo padrão de resposta/orquestração.",
            "Adicionar validações de consistência para entradas de telemetria em lote.",
            "Adicionar importação dedicada para `XLSX` mantendo o mesmo fluxo (preview -> validação -> gravação).",
            "Melhorar reconciliação automática de nomes de furo com regras de normalização/fuzzy matching configurável por empresa.",
            "Concluir rollout operacional da migração `dispositivos.0006_importacaodispositivohistorico` em todos os ambientes (local e servidor).",
        ],
        "falta_fazer": [
            "API pública para ingestão externa com autenticação forte e versionamento.",
            "Observabilidade detalhada por dispositivo (latência, erro, disponibilidade).",
        ],
        "estado_logica": "Boa evolução e já bastante madura: fluxo MagCruiser funcional, histórico ativo e views principais de Dispositivos mais leves após extração de API flow, contexto de páginas e captura serial; pendências focadas em expansão de formatos e API externa.",
    },
    "projetos": {
        "nome": "Projetos",
        "descricao": "Gestão principal do negócio: projetos, furos, registos, materiais, medições e equipa.",
        "feito": [
            "Fluxos completos para projetos/furos/medições/materiais e operações de campo.",
            "Várias rotas já migradas para services/selectors (empregados, stock, acesso contextual, sugestões).",
            "Suporte a contas individual e empregado com regras específicas de acesso.",
            "Refatorações de UI/UX em páginas de furo 3D e detalhe, incluindo melhorias mobile.",
            "Fluxo de avarias de máquinas com atribuição de responsável, atualização por responsável e notificações por email para envolvidos.",
            "Lista de despesas da empresa evoluída com ações por registo (ver, editar e apagar), incluindo detalhe e confirmação de remoção.",
            "Formulário de despesa atualizado com botão de voltar sem gravar.",
            "Nova camada de separação aplicada em `views/materiais.py`: fluxos de criação/edição e movimentos (levantamento/devolução) consolidados com helpers de orquestração.",
            "Nova camada adicional em `views/materiais.py`: fluxos de entrada/saída de stock e pipeline de formulário create/update passaram a builders em `services/stock.py`, reduzindo repetição na view.",
            "Nova camada adicional em `views/materiais.py`: fluxo GET/POST de levantamento/devolução (initial + bind + submissão) movido para `processar_fluxo_movimento_material_form` em `services/stock.py`.",
            "Nova camada de separação aplicada em `views/despesas.py`: resolução de contexto (admin/individual) e submissão de formulários centralizadas.",
            "Nova camada adicional em `views/despesas.py`: update e delete administrativo agora também orquestrados por service (`processar_submissao_form_despesa_update` e `processar_acao_apagar_despesa`).",
            "Nova camada adicional em `views/despesas.py`: fluxos GET/POST de create/update (admin/individual) unificados em builder (`processar_fluxo_form_despesa`) no `services/despesas.py`.",
            "Nova camada de separação aplicada em `views/registos.py`: submissões de create/update (empregado/admin) e renderização de formulário padronizadas.",
            "Nova camada adicional em `views/registos.py`: fluxos POST/GET de formulário (empregado e admin) extraídos para builders em `services/registos.py`, reduzindo duplicação nas views.",
            "Nova camada de separação aplicada em `views/configuracao_perfuracao.py`: tratamento de `ValidationError` e pipeline create/update (admin/empregado) unificados.",
            "Nova camada adicional em `views/configuracao_perfuracao.py`: fluxos GET/POST de create/update (admin/empregado) movidos para builder em `services/configuracao_perfuracao.py` (`processar_fluxo_form_configuracao_perfuracao`).",
            "Nova camada de separação aplicada em `views/medicoes.py`: render de formulário padronizado e redução de repetição nos fluxos create/update.",
            "Nova camada de separação aplicada em `views/projetos.py`: helpers para `empresa_id`, fluxo de formulário create/update e simplificação de associação de empregado.",
            "Nova camada de separação aplicada em `views/empregados.py`: fluxos de formulário create/update de empregado e adicionar/editar ligação de projeto centralizados em builders de `services/empregados.py`.",
            "Nova camada adicional em `views/empregados.py`: fluxo GET/POST de adição de ficheiro ao empregado centralizado em `processar_fluxo_ficheiro_empregado_admin_form` no service.",
            "Nova camada de separação aplicada em `views/empregado_area.py`: renderização de formulários de edição (individual/empregado) padronizada.",
            "Nova camada adicional em `views/empregado_area.py`: fluxos GET/POST de edição de dados (individual e empregado) extraídos para builders em `services/empregado_area.py`.",
            "Nova camada de separação aplicada em `views/opcoes.py`: resolução de contexto admin e submissão de preferências/definições financeiras centralizadas.",
            "Nova camada adicional em `views/opcoes.py`: fluxos GET/POST de preferências e definições financeiras consolidados em builders no `services/opcoes.py`.",
            "Nova camada de separação aplicada em `views/maquina_avarias.py`: criação de avarias (admin/empregado) unificada com helpers de orquestração.",
            "Nova camada adicional em `views/maquina_avarias.py`: fluxos GET/POST de create/update de avarias migrados para builders em `services/maquina_avarias.py`.",
            "Nova camada de separação aplicada em `views/definicoes.py`: processamento de preferências e ativação de idioma encapsulados em helpers dedicados.",
            "Nova camada adicional em `views/definicoes.py`: fluxo GET/POST do formulário de preferências movido para builder em `services/definicoes.py`.",
            "Nova camada de separação aplicada em `views/maquinas.py`: criação/edição com pipeline de formulário unificado e renderização de formulário padronizada.",
            "Nova camada adicional em `views/maquinas.py`: fluxo create/update delegado para `processar_fluxo_form_maquina` em service, reduzindo duplicação de orquestração HTTP.",
            "Nova camada de separação aplicada em `views/empregado_furo.py`: preparação/renderização de formulário de ligação trabalhador-furo extraídas para helpers reutilizáveis.",
            "Tradução i18n avançada em múltiplos templates operacionais e dashboards.",
            "Revisão final de tradução nos principais templates de detalhe, listagens, exportação e dashboards.",
            "Nova camada de separação em furos concluída: contexto de detalhe, resolução de acesso 3D, fluxos create/list/update, delete e importação 3D externa movidos para services.",
            "Nova camada adicional em `views/furos.py`: orquestração GET/POST de create/update consolidada em builders (`processar_fluxo_form_furo_create`/`processar_fluxo_form_furo_update`) no `services/furo_fluxos.py`.",
            "Lógica pesada do gráfico 3D de furos extraída para service dedicado (`furo_3d_chart`), reduzindo significativamente a complexidade da view.",
            "Uniformização visual em curso: várias páginas críticas já migradas para paleta de botões consistente e menos saturada.",
            "3D avançado evoluído com exportação técnica no Implicit Model (CSV da seleção + JSON técnico com pontos filtrados, resumo por domínio e metadados de filtros).",
            "3D avançado evoluído com camada analítica inicial no Implicit Model (extensões X/Y/Z, volume envolvente e estimativa por domínio litológico).",
            "3D avançado evoluído com exportação técnica no Block Model (CSV da seleção + JSON técnico com resumo e filtros ativos).",
            "Paridade de persistência de configuração concluída entre Block Model e Implicit Model: reabertura fiel por modelo com sincronização para `resumo_json` em backend.",
            "Estado da fase 3D avançado registado: núcleo funcional concluído em Wireframe, Block e Implicit (upload, preview, filtros, animações, exportação técnica e persistência de configuração).",
            "Implicit Model evoluído com slice planes interativos (eixo X/Y/Z + posição + plano visual + contagem de pontos visíveis) sem reset de câmara.",
            "Implicit Model evoluído com preenchimento geológico por domínio via zonas extrudidas e controlo de espessura da zona.",
            "Extrusão geológica evoluída para modo unidirecional com heurística por `solo` e override manual (`auto`, `forçar para baixo`, `forçar para cima`).",
            "Implicit Model evoluído com interpolação/suavização configurável (níveis 1-3) para superfícies mais contínuas.",
            "Iso-linhas no Implicit Model entregues com plano selecionável (X/Y/Z), número de níveis, intensidade visual e modo alto contraste (neon).",
            "Legenda técnica das iso-linhas entregue (por domínio, eixo, faixa numérica e níveis), incluindo marcação por cor do domínio.",
            "Navegação técnica do gráfico evoluída com ações `Focar seleção` e `Limpar foco` para recentrar rapidamente análise filtrada.",
            "Comparação temporal A/B no Implicit Model entregue com overlay de modelo B, resumo de diferenças por domínio e persistência de estado de UI.",
            "Delta espacial A/B entregue no Implicit Model com marcadores de ganho/perda (+/-), casca volumétrica opcional e controlos dedicados de opacidade/tamanho.",
            "Presets de visualização técnica por perfil entregues no Implicit Model (Operacional, Geologia, Supervisão).",
            "Block Model profissional evoluído para renderização em voxels/cubos 3D reais (`mesh3d`), com fallback automático para pontos em cenários pesados.",
            "Block Model profissional com estabilidade de câmara entregue: alterações de filtros/opções já não fazem reset de zoom/pan/rotação.",
            "Block Model profissional com escala visual de blocos e redução inteligente de labels de furos para evitar sobreposição.",
            "Block Model profissional com infill inicial implementado (preenchimento vertical por coluna + lateral por vizinho) para volume mais contínuo entre furos.",
            "Hardening de rotas concluído para colisões de slug vs ações (`editar/apagar/3d`) em furos, projetos e empregados.",
            "CONCLUIDO · [GESTAO EMPRESA] Novo menu `Gestão` adicionado para contas de empresa/admin, com atalhos estruturais para controlo transversal da operação.",
            "CONCLUIDO · [GESTAO EMPRESA] Hub inicial criado com páginas base para: Clientes & Contratos, Planeamento, RH & Assiduidade, Compras & Fornecedores, Compliance & Segurança, Centro de Notificações e Relatórios Executivos.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` fase 1 entregue com modelo persistente, migração e CRUD completo (lista, criar, detalhe, editar e apagar).",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento` fase 1 entregue com modelo persistente de turnos, migração e CRUD base (lista, criar, editar e apagar).",
            "CONCLUIDO · [GESTAO EMPRESA] `RH & Assiduidade` fase 1 entregue com modelo persistente, migração e CRUD base (lista, criar, editar e apagar).",
            "CONCLUIDO · [GESTAO EMPRESA] `Compras & Fornecedores` fase 1 entregue com dashboard operacional (KPIs, categorias de despesa e últimas compras).",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` fase 1 entregue com monitorização de avarias, riscos e estado documental base.",
            "CONCLUIDO · [GESTAO EMPRESA] `Centro de Notificações` fase 1 entregue com fila de pendências por prioridade (empregados, assiduidade, avarias e planeamento).",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` fase 1 entregue com KPIs globais e tendência mensal de despesas.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compras & Fornecedores` fase 2 parcial: pedidos de compra com criação e aprovação/rejeição.",
            "CONCLUIDO · [GESTAO EMPRESA] `Centro de Notificações` fase 2 parcial: notificações com responsável, prazo e estado (SLA operacional).",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` fase 2 parcial: exportação direta em CSV e XLSX.",
            "CONCLUIDO · [GESTAO EMPRESA] `Centro de Notificações` evolução: filtros por estado/prioridade, SLA calculado (OK/Em risco/Atrasado) e mudança rápida de estado.",
            "CONCLUIDO · [GESTAO EMPRESA] `Centro de Notificações` evolução: exportação CSV com filtros aplicados.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compras & Fornecedores` evolução: tabela de categorias e últimas despesas visível no mesmo painel.",
            "CONCLUIDO · [GESTAO EMPRESA] `Pedidos de compra` evolução: editar/apagar disponíveis além de aprovar/rejeitar.",
            "CONCLUIDO · [GESTAO EMPRESA] `Notificações` evolução: editar/apagar disponíveis além de atualização de estado.",
            "CONCLUIDO · [GESTAO EMPRESA] Hub de Gestão evoluído com KPI de SLA vencido e pendências principais.",
            "CONCLUIDO · [GESTAO EMPRESA] `RH & Assiduidade` evolução: ações e exportações reorganizadas em grupos visuais, corrigindo quebra vertical dos botões.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: filtros por cliente/estado/projeto/vencimento + KPIs de vencidos e alertas de 7/30 dias.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compras & Fornecedores` evolução: filtros operacionais (estado, prioridade, projeto, categoria, pesquisa) e exportação de pedidos em CSV/XLSX com filtros aplicados.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: modelos persistentes de Checklist HSE e Incidente, com CRUD completo, mudança de estado e painel operacional com filtros.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: auditorias HSE e ações corretivas persistentes, com CRUD, mudança de estado, prazos e integração no painel de compliance.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` integrado nos Relatórios Executivos com métricas adicionais de auditorias e ações corretivas.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: evidências/anexos por checklist, incidente, auditoria e ação corretiva, com listagem recente e gestão segura de ficheiros.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: fecho formal das ações corretivas com data, resumo de execução, validação de eficácia e trilho persistente.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: planos de auditoria recorrente com geração automática de auditorias vencidas diretamente no painel.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: ações preventivas persistentes com CRUD, mudança de estado, prazo, evidências e integração total no painel.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` integrado nos Relatórios Executivos com métricas de planos vencidos e ações preventivas abertas/vencidas.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: dashboard de eficácia por responsável e por projeto, com taxa de fecho, vencidos, tendência mensal e leitura de risco.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: SLA por prioridade, tempo médio de fecho e alertas automáticos para ações críticas vencidas, integrados com o Centro de Notificações.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: comparativos históricos mensais, benchmark por responsável/equipa (função) e alertas preditivos antes do vencimento por criticidade.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: drill-down por projeto/responsável, tendência trimestral e previsão de incumprimento por carga aberta.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: scoring de risco ajustável por empresa, com pesos/limiares configuráveis em `Definições` e impacto direto nas previsões por responsável/projeto.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: drill-down clicável até à ação concreta e previsão enriquecida com histórico real de SLA, taxa de fecho e tempo médio por responsável/projeto.",
            "CONCLUIDO · [GESTAO EMPRESA] `Compliance & Segurança` evolução: filtros temporais avançados (total/7/30/90 dias), snapshots comparativos entre janelas e exportação CSV do dashboard de eficácia.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` evolução: filtro por período (início/fim), resumo consolidado (Financeiro + RH + Compliance) e exportação CSV/XLSX alinhada com os filtros.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` evolução: comparativo financeiro por projeto (metros, registos, custo, receita estimada, margem) visível no ecrã e exportado em CSV/XLSX.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` evolução: envio por email com destinatários configuráveis e anexos CSV/XLSX respeitando os filtros aplicados.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` evolução: agendamento automático (diário/semanal/mensal), execução imediata manual e comando de processamento pendente para servidor.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` evolução: exportação PDF disponível no painel + envio de anexo PDF (manual e agendado).",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` evolução: layout PDF executivo com branding, cabeçalho, paginação, cartões KPI e secções visuais por área.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` refinado com hero executivo, resumo textual automático e fallback seguro para logótipos não suportados pelo motor PDF.",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento` evolução: filtros operacionais (estado, turno e período), deteção automática de conflitos de recurso (empregado/máquina) e resumo de capacidade por turno/estado.",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento` evolução: botão `Resolver` por conflito com página dedicada (A/B lado a lado), links diretos de edição e ações rápidas de estado (confirmar/cancelar).",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento` evolução: resolução automática de conflitos (cancela menor prioridade; empate: mantém confirmado; empate final: mantém o mais antigo).",
            "CONCLUIDO · [GESTAO EMPRESA] `Compras & Fornecedores` evolução: cadastro de fornecedores (SLA e avaliação), propostas por pedido e comparação automática com scoring de preço/prazo (incluindo seleção rápida).",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatórios Executivos` evolução: histórico/auditoria de envios (manual, agendado e executar agora) com estado, destinatários, anexos e erro técnico.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: anexos de contrato, adendas contratuais, configuração de renovação automática e janela de alerta por contrato, com detalhe comercial reforçado.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: histórico real de renovações, adendas editáveis e leitura financeira acumulada por contrato com vencimento efetivo.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: alertas comerciais operacionais (vencimento, suspensão, follow-up e ausência de contacto) e timeline comercial por cliente/contrato.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: exportação documental consolidada do contrato em dossiê ZIP com ficha PDF, manifesto, anexos e adendas.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: workflow comercial simples (`Estável`, `Em negociação`, `Renovação pendente`, `Renovado`, `Perdido`) com filtro e leitura visual na lista/detalhe.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: histórico persistente de mudança de workflow comercial, com observação opcional, utilizador responsável e integração no detalhe/timeline.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: workflow comercial assistido com transições sugeridas por vencimento, follow-up, suspensão e renovação, visíveis na lista e no detalhe.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: aplicação rápida da sugestão principal de workflow diretamente no detalhe do contrato, com registo automático em histórico.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: painel comercial consolidado por cliente, agrupando contratos, alertas, follow-ups, workflow sugerido e valor estimado numa vista única.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: ficha de cliente separada do contrato, com contactos agregados, portfolio contratual e histórico comercial consolidado.",
        ],
        "proximos_passos": [
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: timeline comercial própria do cliente, juntando eventos da ficha comercial com renovações, adendas, estados e contactos-chave.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: exportação individual em PDF da ficha comercial do cliente, separada do dossiê ZIP do contrato.",
            "CONCLUIDO · [GESTAO EMPRESA] `Clientes & Contratos` evolução: edição dedicada da ficha de cliente com contactos principais, contactos secundários, notas comerciais e classificação comercial própria.",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento` evolução: calendário visual semanal/mensal com navegação temporal, leitura operacional por turno/dia e destaque de conflitos/capacidade.",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento` evolução: turnos configuráveis por máquina, com horário oficial obrigatório por equipamento e aplicação automática no planeamento.",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento` evolução: nome identificável por planeamento, com fallback automático e leitura reforçada em listas, conflitos e calendário.",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento`/`Registos` evolução: o registo diário do empregado já pode selecionar o planeamento cumprido, herdando automaticamente projeto, furo, data e horário base do turno.",
            "CONCLUIDO · [GESTAO EMPRESA] `Planeamento`/`Registos` evolução: o formulário do empregado destaca visualmente os turnos disponíveis para a data do registo, acelerando a escolha do planeamento cumprido.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução: novo modelo `Relatório de Turno` ligado ao registo diário, com formulário técnico detalhado integrado no ecrã de novo registo/edição.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução: clarificação de UX entre `Registo Operacional` e `Relatório Técnico do Turno`, deixando a ficha técnica como extensão opcional do registo.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução: página própria do `Relatório Técnico do Turno` com leitura estruturada por secções e exportação PDF para empregado e admin.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução: edição dedicada do `Relatório Técnico do Turno`, permitindo corrigir apenas a ficha técnica sem reabrir o registo operacional completo.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução: listagem própria dos `Relatórios Técnicos do Turno`, separada dos registos e com filtros por empregado, projeto, furo, período e texto.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução: exportação consolidada dos `Relatórios Técnicos do Turno` em ZIP, respeitando os filtros aplicados na listagem.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução: exportações CSV/XLSX/PDF consolidado dos `Relatórios Técnicos do Turno` e dashboard-resumo por projeto, turno e máquina na listagem.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução: dashboard técnico dos relatórios com avanço total, recuperação média, horas de paragem, ocorrências por tipo e leitura analítica por projeto, turno e máquina.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` regra de acesso: empregado consulta relatórios técnicos, mas exportações e downloads ficam reservados à empresa no menu `Registos`.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` UX de empregado refinada: relatórios técnicos em modo consulta simples, sem ações de edição/exportação no detalhe e na listagem.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` ajustado à ficha real: `reaming`, `medição de desvio`, `cimentação`, `lavar furo` e `varas presas` em `Sim/Não`, com 4 campos de `Especialista` e 4 de `Servente` por turno.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` evolução: cada `Especialista` e `Servente` passou a ter campo próprio de horas trabalhadas, refletido no formulário, detalhe e exportações.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` refinado com `Manobra`, `Entubamento`, `Avaria` e `Bit novo` em `Sim/Não`, incluindo detalhe e dashboard coerentes.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` ajustado com horários `de/até` por operação/ocorrência e remoção de `Bit velho`, refletido no formulário, detalhe e exportações.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` refinado com `Horas paragem` em `Sim/Não + de/até`, mantendo o cálculo total de paragem no dashboard técnico.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` refinado com defaults em `Não` para todos os campos `Sim/Não` da secção `Operações e ocorrências`, evitando novos relatórios com valores vazios.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` refinado com `Polímeros` em 4 campos de texto independentes, preservando o histórico anterior no primeiro campo.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` refinado com lista dinâmica de `Polímeros` (campo único + botão `+`), substituindo os campos fixos e preservando o histórico já registado.",
            "CONCLUIDO · [GESTAO EMPRESA] `Relatório Técnico do Turno` reorganizado: campos-chave de turno (`No início`, `No final`, `Avanço do turno`, `Testemunho recuperado`, `Percentagem de recuperação`) movidos para `Informação`.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` evolução estrutural: a ficha técnica do turno passou a viver no próprio `Registo Diário`, com migração segura dos dados antigos e manutenção das páginas/listagens/exportações existentes.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` limpeza estrutural: o modelo legacy `RelatorioTurno` foi removido do runtime e ficou substituído em definitivo pelo próprio `Registo Diário`.",
            "CONCLUIDO · [GESTAO EMPRESA] `Informação Técnica` evoluída com lista dinâmica de `Furadas do turno`, permitindo adicionar múltiplas linhas horizontais (`início`, `fim`, `avanço`, `recuperação`, `rocha`, `descrição`) no mesmo registo.",
            "CONCLUIDO · [GESTAO EMPRESA] `Informação Técnica` refinada com edição direta das `Furadas do turno`, incluindo botões `Editar`, `Guardar edição` e `Cancelar edição` por linha.",
            "CONCLUIDO · [GESTAO EMPRESA] `Informação Técnica` refinada com ordenação manual das `Furadas do turno`, incluindo ações rápidas de subir/descer para corrigir a sequência.",
            "CONCLUIDO · [GESTAO EMPRESA] `Informação Técnica` refinada com numeração visual das `Furadas do turno` e totais automáticos de `avanço` e `recuperação` no fim da lista.",
            "CONCLUIDO · [GESTAO EMPRESA] `Informação Técnica` refinada com resumo de `Furadas do turno` também no detalhe e no PDF, incluindo total de linhas, avanço total e recuperação total.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` e `Fichas Técnicas` refinados com leitura rápida de `Furadas`, `Avanço das furadas` e `Recuperação das furadas` diretamente nas listagens.",
            "CONCLUIDO · [GESTAO EMPRESA] `Registos` e `Fichas Técnicas` refinados com destaque visual nas listagens para `0 furadas`, baixa quantidade de linhas e `recuperação abaixo do avanço`, facilitando a leitura rápida da empresa.",
            "CONCLUIDO · [GESTAO EMPRESA] `Informação Técnica` refinada com lista dinâmica de `Operações e ocorrências`, permitindo adicionar múltiplas linhas de tipo + `de` + `até`, preservando compatibilidade com o detalhe, PDF e métricas já existentes.",
            "CONCLUIDO · [GESTAO EMPRESA] `Informação Técnica` refinada com lista dinâmica de `Equipa`, permitindo adicionar múltiplas linhas de `Função` + `Nome` + `Horas`, preservando compatibilidade com o detalhe, PDF e dados antigos de especialistas/serventes.",
            "[NOVA FASE · GESTAO EMPRESA] Evoluir `RH & Assiduidade` com aprovação multi-nível, banco de horas, saldos por colaborador e exportação para payroll.",
            "[NOVA FASE · GESTAO EMPRESA] Evoluir `Compras & Fornecedores` com cadastro de fornecedor, pedidos de compra, propostas e scoring.",
            "[NOVA FASE · GESTAO EMPRESA] Evoluir `Compliance & Segurança` com exportação XLSX do dashboard de eficácia.",
            "[NOVA FASE · GESTAO EMPRESA] Evoluir `Compliance & Segurança` com exportação PDF do dashboard de eficácia.",
            "[NOVA FASE · GESTAO EMPRESA] Evoluir `Compliance & Segurança` com alertas por tendência (agravamento, estabilização e melhoria de risco).",
            "[NOVA FASE · GESTAO EMPRESA] Evoluir `Compliance & Segurança` com presets de leitura por perfil (`Direção`, `Obra` e `HSE`).",
            "[NOVA FASE · GESTAO EMPRESA] Evoluir `Centro de Notificações` com atribuição, SLA, histórico e envio automático.",
            "[NOVA FASE · GESTAO EMPRESA] Evoluir `Relatórios Executivos` com benchmarks por responsável/projeto, snapshots comparativos e distribuição automática por perfil.",
            "Continuar migração de lógica restante de views para camadas dedicadas, com foco em módulos ainda densos de operação e registos técnicos.",
            "Unificar validações de domínio críticas (ex.: regras de inclinação por tipo de furo).",
            "Reforçar testes de regressão para permissões entre superuser/admin/empregado/individual.",
            "Fechar i18n residual em mensagens transversais e textos técnicos específicos.",
            "Aplicar o mesmo padrão de orquestração por fluxos nas views restantes de operações e registos técnicos.",
            "Concluir varredura visual final para remover estilos legacy com cores vivas remanescentes em templates menos usados.",
            "Plano 3D avançado (1/10): normalizar ingestão de dados 3D (OBJ/CSV/JSON/LAS), com validação robusta e mensagens de erro claras.",
            "Plano 3D avançado (2/10): consolidar o pipeline de geometria em pontos 3D normalizados (X, Y, Z), preservando metadados por domínio litológico.",
            "Plano 3D avançado (3/10): reforçar modelo Wireframe com controlo de camadas e estados visuais persistentes por utilizador.",
            "Plano 3D avançado (4/10): evoluir Block Model para voxels configuráveis (resolução/tamanho), com filtros por intervalos e domínio.",
            "Block Model profissional (próximo): adicionar toggle para mostrar/ocultar células inferidas e comparar rapidamente com células medidas reais.",
            "Block Model profissional (próximo): adicionar métricas de confiança da inferência por célula e filtros por confiança/distância.",
            "Block Model profissional (próximo): otimizar renderização para volumes grandes (simplificação dinâmica por zoom e agregação por tiles).",
            "Block Model profissional (próximo): reforçar QA visual com cenários de regressão (labels, escala, câmara, fallback e performance).",
            "Plano 3D avançado (5/10): amadurecer Implicit Model com modos Delaunay/Convex Hull estáveis, alternância por checkbox e sem reset de câmara.",
            "Plano 3D avançado (6/10): adicionar animações opcionais por checkbox (rotação, pulso, relevo/terreno), mantendo a pose atual da câmara.",
            "Plano 3D avançado (7/10): enriquecer paleta geológica com mapeamento padrão por rocha (granito, quartzo, xisto, pirite, minério, argila, jaspe e variantes).",
            "Plano 3D avançado (8/10): concluído para Block/Implicit no estado atual (configuração visual persistida em `resumo_json` + reabertura fiel por modelo).",
            "Plano 3D avançado (9/10): concluído para Block/Implicit no estado atual (exportação técnica CSV/JSON com seleção ativa e metadados).",
            "Plano 3D avançado (10/10): concluído em fase inicial (métricas rápidas e volumetria envolvente; próximo passo: cortes e comparação temporal).",
            "[Curto prazo] Roadmap de equiparação (1/8): evoluir motor geológico para modelação implícita avançada com interpolação robusta, constraints, faults e domaining assistido.",
            "[Curto prazo] Roadmap de equiparação (4/8): reforçar performance para grande escala (milhões de pontos/blocos, renderização e consultas otimizadas).",
            "[Curto prazo] Roadmap de equiparação (5/8): expandir integrações industriais (DXF/DWG/LAS/APIs) e sincronização com ERPs/sensores/equipamentos.",
            "[Médio prazo] Roadmap de equiparação (2/8): adicionar camada completa de planeamento mineiro (design, fases, sequenciamento e comparação de cenários).",
            "[Médio prazo] Roadmap de equiparação (6/8): reforçar governança e compliance (auditoria, versionamento técnico, permissões granulares e aprovação por workflow).",
            "[Médio prazo] Roadmap de equiparação (7/8): aumentar automação inteligente (alertas preditivos, recomendações operacionais e assistente técnico contextual).",
            "[Longo prazo] Roadmap de equiparação (3/8): implementar geoestatística e estimativas (variografia, kriging, classificação de recursos/reservas e auditoria técnica).",
            "[Longo prazo] Roadmap de equiparação (8/8): consolidar camada enterprise (testes de carga, documentação técnica, suporte e onboarding em escala).",
            "[Próxima fase 3D] Evoluir métricas volumétricas para além de bounding box (estimativa por malha/superfície e por domínio).",
            "[Próxima fase 3D] Aplicar otimizações finais de performance para datasets de maior escala (render e filtros em tempo real).",
            "[Próxima fase 3D] Adicionar comparação lado-a-lado entre modelos (A/B) com sincronização de câmara e diferenças por domínio.",
        ],
        "falta_fazer": [
            "API versionada para mobile/sensores/drones com contratos estáveis.",
            "Histórico temporal completo de evolução de furo com consultas otimizadas.",
            "Concluir robustez final do Block Model profissional para grande escala (confiança geológica + performance + testes automatizados).",
        ],
        "estado_logica": "Boa e em aceleração: além do núcleo de furos, também materiais, despesas (incluindo update/delete), registos, configuração de perfuração, medições, projetos/opções, definições e avarias já receberam nova camada de separação; no 3D avançado, Block/Implicit já contam com persistência backend, exportação técnica, cortes, iso-linhas avançadas, extrusão geológica, presets por perfil, comparação temporal A/B e controlo de foco, restando agora sobretudo volumetria mais precisa e otimização para escala.",
    },
    "ia": {
        "nome": "IA",
        "descricao": "AI Visual, chatbox operacional, memória de trabalho e biblioteca documental.",
        "feito": [
            "Hub IA, chatbox, memória operacional e histórico de análises disponíveis.",
            "Suporte a biblioteca de documentos para contexto operacional da IA.",
            "Exportação/limpeza de datasets IA disponível na área de úteis (superuser).",
            "Melhorias na experiência do chatbox e base para fluxos de respostas guiadas clicáveis.",
        ],
        "proximos_passos": [
            "Aumentar qualidade de OCR e pipelines por zona configurável.",
            "Consolidar leitura multimodal e pós-processamento semântico por domínio.",
            "Estruturar serviços de resposta guiada com sugestões clicáveis em mais cenários.",
        ],
        "falta_fazer": [
            "RAG/API versionada com controles de permissão por empresa/projeto.",
            "Métricas de qualidade por tipo de documento e feedback loop contínuo.",
        ],
        "estado_logica": "Intermédio: núcleo funcional em produção, com refatoração contínua para serviços especializados.",
    },
    "geologia": {
        "nome": "Geologia",
        "descricao": "Operação geológica, integração drone e suporte técnico de terreno.",
        "feito": [
            "CONCLUIDO · Hub geologia e interfaces de drone integrados no ecossistema principal.",
            "CONCLUIDO · Refatorações recentes já moveram partes de submissão para services dedicados.",
            "CONCLUIDO · Tradução i18n reforçada em páginas principais de missão/log e dashboard de furo geológico.",
            "CONCLUIDO · Fluxos de logs geológicos (create/update/anexo) agora orquestrados em service dedicado, com views mais leves.",
            "CONCLUIDO · Nova camada adicional em `geologia/views/logs.py`: fluxos GET/POST de create/update/anexo unificados em builders no `services/logs.py` (`processar_fluxo_*`).",
            "CONCLUIDO · Fluxos de drone (comandos, importação de missão e missão create/update) extraídos para service, reduzindo lógica inline nas views.",
            "CONCLUIDO · Camada Drone S_F também evoluída: criação de comando passou a usar builders/processadores em service (`drone_sf_dashboard`).",
            "CONCLUIDO · APIs bridge do Drone S_F (ingest/comandos/confirmar/log) agora usam resolução comum de autorização em service, removendo repetição nas views.",
            "CONCLUIDO · Ações de missão programada S_F (toggle/executar/remover) extraídas para service, deixando `dashboard.py` mais focado em HTTP/UI.",
            "CONCLUIDO · Nova camada de separação aplicada em `geologia/views/drone.py`: validação de empresa necessária e pipeline de formulário de missão (create/update) consolidados em helpers.",
            "CONCLUIDO · Nova camada de separação aplicada em `geologia/views/dashboard.py`: tratamento de ações POST do detalhe de operação e criação de comando S_F centralizados em helpers.",
            "CONCLUIDO · Nova camada de separação aplicada em `geologia/views/dashboard.py`: fluxos POST do detalhe de operação S_F e criação de comando movidos para `services/drone_sf_page.py`, reduzindo lógica de orquestração na view.",
            "CONCLUIDO · Nova camada aplicada nos endpoints bridge S_F: resolução de contexto (autorização + operação + payload JSON) unificada em helper de service (`resolver_contexto_bridge_sf`), reduzindo duplicação nas APIs de ingest/comandos/confirmação/log.",
            "CONCLUIDO · Nova camada de separação aplicada em `geologia/views/drone.py`: fluxo create/update de missão consolidado em builder `processar_fluxo_form_missao` no service, reduzindo lógica repetida de POST/GET.",
            "CONCLUIDO · Nova camada adicional em `geologia/views/drone.py`: fluxo de importação de missão DJI no hub consolidado em `processar_fluxo_importacao_missao` no service.",
            "CONCLUIDO · Nova camada adicional em `geologia/views/drone.py`: fluxos de atualização do controlo e criação de comando movidos para builders em `services/drone_dashboard.py`.",
            "CONCLUIDO · Nova camada adicional em `geologia/views/dashboard.py`: ações de missão programada S_F (toggle/executar/remover) unificadas em helper único de service (`processar_acao_missao_programada_sf`).",
            "CONCLUIDO · Regra de histórico TO DO aplicada em Geologia: tarefas concluídas mantidas no registo e marcadas com `CONCLUIDO`, sem apagar entradas antigas.",
            "CONCLUIDO · [ATALHOS GEOLOGO · MELHORIA] Planeamento de amostragem: atalho para definir próximos intervalos por furo e evitar falhas de cobertura.",
            "CONCLUIDO · [ATALHOS GEOLOGO · MELHORIA] Qualidade de dados: validações rápidas (intervalos vazios, litologia em falta, anexos em falta e conflitos pendentes).",
            "CONCLUIDO · [ATALHOS GEOLOGO · MELHORIA] Correlações geologia × perfuração: comparar litologia com ROP, desgaste, consumo e desvios de trajetória.",
            "CONCLUIDO · [ATALHOS GEOLOGO · MELHORIA] Mapa de furos 2D/3D: visão espacial única com estado dos furos e acesso direto aos logs.",
            "CONCLUIDO · [ATALHOS GEOLOGO · MELHORIA] Relatórios rápidos: exportação em 1 clique (diário/semanal por furo/projeto).",
            "CONCLUIDO · [ATALHOS GEOLOGO · MELHORIA] Alertas prioritários: entrada dedicada para alertas críticos ordenados por risco.",
            "CONCLUIDO · [ATALHOS GEOLOGO · MELHORIA] Pendências da equipa: lista de tarefas abertas do geólogo (logs por validar, conflitos, furos sem log recente).",
            "CONCLUIDO · [ATALHOS GEOLOGO · PRIORIDADE] Pendentes de validação: fila de logs criados por turno/equipa para aprovação/rejeição rápida pelo geólogo.",
            "CONCLUIDO · [ATALHOS GEOLOGO · PRIORIDADE] Intervalos em conflito: deteção automática de sobreposição de intervalos no mesmo furo com ações de correção.",
            "CONCLUIDO · [ATALHOS GEOLOGO · PRIORIDADE] Mapa litológico do furo: coluna visual por profundidade com cores por litologia e filtros operacionais.",
            "CONCLUIDO · [ATALHOS GEOLOGO · PRIORIDADE] Alertas geotécnicos: lista de zonas com RQD baixo, fraturação elevada, presença de água e anomalias associadas.",
            "CONCLUIDO · [ATALHOS GEOLOGO · PRIORIDADE] Exportar relatório geológico: PDF/Excel por furo/projeto com logs, anexos, missões e resumo técnico.",
        ],
        "proximos_passos": [
            "[CURTO PRAZO · LOGICA] Migrar restantes ações de escrita e importação para services/selectors.",
            "[CURTO PRAZO · LOGICA] Continuar a refatoração dos endpoints bridge para manter padrão único de resposta/orquestração em API.",
            "[CURTO PRAZO · OPERACAO] Padronizar validações de missão e trilhas de auditoria operacionais.",
            "[CURTO PRAZO · QUALIDADE] [NOVA FASE · Segurança/Dados] Reforçar isolamento multiempresa para nunca expor dados entre empresas e adicionar testes de regressão para permissões e consulta.",
            "[CURTO PRAZO · ARQUITETURA] [NOVA FASE · Arquitetura] Garantir padrão limpo com `services/`, `selectors/`, URLs em `url_patterns/`, mensagens, logger `core`, permissões (`@login_required`, `@admin_required`) e zero lógica pesada em views.",
            "[CURTO PRAZO · DASHBOARD GEOLOGO] Timeline do turno com últimos logs criados/alterados, conflitos novos e alertas críticos.",
            "[CURTO PRAZO · DASHBOARD GEOLOGO] Semáforo por furo (verde/amarelo/vermelho) para qualidade dos dados: sem log recente, intervalos por validar e anexos em falta.",
            "[CURTO PRAZO · DASHBOARD GEOLOGO] Top 5 furos prioritários com regras de urgência e acesso direto à ação.",
            "[CURTO PRAZO · DASHBOARD GEOLOGO] Atalhos de ação imediata no topo: Novo Log, Validar Pendentes, Resolver Conflitos e Abrir Mapa Litológico.",
            "[CURTO PRAZO · DASHBOARD GEOLOGO] Resumo geotécnico diário automático por projeto (RQD, fraturação, água) com comparação ao dia anterior.",
            "[CURTO PRAZO · DASHBOARD GEOLOGO] Painel de produtividade geológica (logs por turno, metros descritos, tempo médio de validação de conflitos).",
            "[CURTO PRAZO · DASHBOARD GEOLOGO] Bloco de comunicação para nota técnica do dia para encarregado/supervisor.",
            "[CURTO PRAZO · DASHBOARD GEOLOGO] Lembretes operacionais (furo sem atualização há 24h, missão drone pendente de revisão, conflitos abertos).",
            "[NOVA FASE] Evoluir Geologia para nível profissional com duas entregas principais: `Block Model 3D profissional` e `Implicit Model 3D simplificado`.",
            "[NOVA FASE · Block Model] Estado atual: núcleo profissional já funcional (list/create/detail/3d/delete, export JSON/CSV técnico, regeneração, voxels reais e infill inicial).",
            "[CURTO PRAZO · BLOCK MODEL] [NOVA FASE · Block Model] Próxima iteração: consolidar qualidade geológica do infill (continuidade por domínio/bancada e score de confiança por célula).",
            "[MEDIO PRAZO · BLOCK MODEL] [NOVA FASE · Block Model] Evoluir os modelos já existentes (`Modelo3DBlock`) com esquema profissional incremental, criando `BlockModelCell` e mantendo compatibilidade com dados atuais.",
            "[MEDIO PRAZO · BLOCK MODEL] [NOVA FASE · Block Model] Implementar services: `gerar_block_model_para_projeto`, `calcular_blocos_a_partir_das_medicoes`, `atribuir_litologia_ao_bloco`, `exportar_block_model_json`.",
            "[MEDIO PRAZO · BLOCK MODEL] [NOVA FASE · Block Model] Implementar selectors: `obter_block_models_projeto`, `obter_celulas_block_model`, `obter_dados_3d_block_model` com foco em queries eficientes para PostgreSQL.",
            "[MEDIO PRAZO · BLOCK MODEL] [NOVA FASE · Block Model] Reforçar as views/templates já existentes (`modelo_3d_block_model` e hub 3D) com fluxo profissional progressivo: list/create/detail/3d/delete, filtros por litologia/profundidade, toggle de furos e opção 'só blocos com dados'.",
            "[MEDIO PRAZO · BLOCK MODEL] [NOVA FASE · Block Model] Entregar resumo técnico na página 3D: total de blocos, volume estimado e litologias encontradas.",
            "[NOVA FASE · Implicit] Após Block Model, evoluir o `Modelo3DImplicit` atual para esquema profissional com `ImplicitModelSurface`, método de interpolação configurável e malha/pontos persistidos.",
            "[MEDIO PRAZO · IMPLICIT] [NOVA FASE · Implicit] Implementar services: `gerar_implicit_model_para_projeto`, `obter_pontos_geologicos_do_projeto`, `interpolar_superficie_litologia`, `gerar_malha_superficie`, `exportar_implicit_model_json`.",
            "[MEDIO PRAZO · IMPLICIT] [NOVA FASE · Implicit] Reforçar selectors e as páginas atuais de Implicit para visualização profissional de superfícies/zonas interpoladas + comparação com furos reais, sem ruptura de UX existente.",
        ],
        "falta_fazer": [
            "API de operações em tempo real com autenticação por dispositivo/operador.",
            "Pipeline de dados espaciais para analytics preditivo.",
            "Motor geológico avançado com block model persistente por célula e implicit model interpolado por litologia pronto para uso operacional.",
        ],
        "estado_logica": "Intermédio/boa e a subir: evolução consistente com redução forte de duplicação em logs/drone/dashboard e bridge. Nova fase aberta para Geologia 3D profissional (Block Model + Implicit) com implementação incremental iniciando por Block Model.",
    },
    "website": {
        "nome": "Website",
        "descricao": "Site público, páginas de entrada e jornada comercial/branding.",
        "feito": [
            "Homepage e estrutura pública funcional em produção.",
            "Ajustes recentes de conteúdo e posicionamento de funcionalidades principais.",
            "Páginas públicas principais já com uso consistente de tags de tradução.",
            "Revisão de consistência i18n na jornada pública (home, planos, login e registo).",
        ],
        "proximos_passos": [
            "Refinar copy comercial por idioma (tom e clareza), mantendo consistência com o produto.",
            "Melhorar prova social, métricas e CTA para conversão.",
        ],
        "falta_fazer": [
            "Funil de aquisição com tracking mais profundo e eventos padronizados.",
            "Páginas técnicas/documentação pública por módulo.",
        ],
        "estado_logica": "Boa para a fase atual, com foco em conteúdo, conversão e internacionalização completa.",
    },
    "infra_devops": {
        "nome": "Infra / Deploy",
        "descricao": "Operação de servidor, deploy contínuo, logs, observabilidade e rotinas de produção.",
        "feito": [
            "Deploy com Gunicorn + Nginx estabilizado e site em produção com HTTPS ativo.",
            "Pipeline operacional manual documentado (git pull, migrate, collectstatic, restart services).",
            "Ajustes de `ALLOWED_HOSTS`, cookies seguros e configuração de ambiente já aplicados em produção.",
            "Sitemap e robots já adicionados para indexação e SEO técnico.",
        ],
        "proximos_passos": [
            "Padronizar script único de deploy (pré-check, migrate, collectstatic, healthcheck e rollback).",
            "Adicionar healthcheck automático pós-deploy (`curl` rotas críticas + validação de login).",
            "Separar logs por serviço/módulo com rotação automática (`logrotate`) e retenção definida.",
            "Configurar alertas de disponibilidade e erros 5xx (email/Slack) com limiares claros.",
            "Automatizar backup de base de dados e media com testes periódicos de restore.",
        ],
        "falta_fazer": [
            "CI/CD com ambiente de staging espelho da produção.",
            "Runbooks de incidente e disaster recovery com RTO/RPO definidos.",
        ],
        "estado_logica": "Intermédio: produção funcional, mas ainda dependente de execução manual e com observabilidade parcial.",
    },
    "seguranca_qualidade": {
        "nome": "Segurança / Qualidade",
        "descricao": "Hardening de aplicação, cobertura de testes, auditoria de permissões e estabilidade funcional.",
        "feito": [
            "Checks de deploy já incorporados no fluxo operacional.",
            "Validações de domínio críticas já iniciadas (ex.: regras de inclinação por tipo de furo).",
            "Permissões por perfil (superuser/admin/empregado/individual) já estruturadas em múltiplos fluxos.",
        ],
        "proximos_passos": [
            "Completar matriz de permissões com testes automatizados por endpoint e por perfil.",
            "Adicionar testes de regressão para fluxos críticos (registo, login, furos, medições, despesas, avarias).",
            "Reforçar proteção de segredos/configuração sensível e revisão de variáveis de ambiente por ambiente.",
            "Executar varredura de segurança em dependências e corrigir CVEs com política de atualização.",
            "Criar bateria de smoke tests para validação rápida após cada release.",
        ],
        "falta_fazer": [
            "Suite E2E completa para jornadas críticas multi-perfil.",
            "Política de versionamento de API com testes de compatibilidade.",
        ],
        "estado_logica": "Boa base com avanços consistentes, mas ainda falta fechar automação de testes e hardening contínuo.",
    },
    "produto_comercial": {
        "nome": "Produto / Comercial",
        "descricao": "Experiência do utilizador, planos/subscrição, onboarding e preparação para escala de clientes.",
        "feito": [
            "Planos e subscrições funcionais com suporte a plano gratuito (valor zero).",
            "Configuração de pagamentos PayPal integrada na plataforma.",
            "Página de sugestões e canais de feedback já disponíveis para utilizadores.",
            "Menu e navegação por perfil bastante evoluídos (empresa, empregado, individual e superuser).",
        ],
        "proximos_passos": [
            "Concluir fluxo robusto de verificação de email e monitorização de entregabilidade SMTP.",
            "Melhorar onboarding guiado por tipo de conta (empresa vs individual) com checklist inicial.",
            "Criar dashboard comercial com métricas de ativação, retenção e conversão por plano.",
            "Definir versão trial/prova com limites de features e mensagens in-app claras.",
            "Refinar UX mobile em páginas operacionais com maior densidade de informação.",
        ],
        "falta_fazer": [
            "Funil completo de aquisição e retenção com eventos de produto padronizados.",
            "Playbook de suporte ao cliente e documentação de onboarding por segmento.",
        ],
        "estado_logica": "Intermédio/alto: núcleo comercial funcional, com foco agora em maturidade de onboarding, métricas e escala.",
    },
}


def listar_todo_areas():
    return [{"slug": slug, **dados} for slug, dados in _AREAS_TODO.items()]


def obter_todo_area(slug):
    try:
        return {"slug": slug, **_AREAS_TODO[slug]}
    except KeyError as exc:
        raise Http404("Área TO DO não encontrada.") from exc


def obter_notas_transversais_todo():
    return {
        "selectors_services": (
            "Estamos a retirar lógica solta para selectors/services em todas as apps. "
            "A base já está bem estruturada e houve avanço forte em Projetos (agora também materiais, registos, configuração de perfuração e medições), Furos/Despesas/Avarias e também em Dispositivos (importação MagCruiser com histórico, API flow padronizado e contexto de páginas extraído para services), mas a migração ainda está em curso nas camadas residuais de views/forms/helpers. "
            "No curto prazo, a prioridade operacional em Dispositivos é garantir a migração `0006_importacaodispositivohistorico` aplicada em todos os ambientes para eliminar dependência de fallback."
        ),
        "traducao": (
            "Estado atual de tradução: revisão ampla concluída nos templates visíveis do utilizador, incluindo Projetos, IA, Geologia, Plataforma e Website. "
            "Pontos pendentes concentram-se sobretudo em mensagens de backend/validação e alguns textos técnicos internos, não no menu principal."
        ),
        "governanca_execucao": (
            "As páginas TO DO foram expandidas para cobertura global ('para tudo'): apps funcionais + frentes transversais de Infra/Deploy, Segurança/Qualidade e Produto/Comercial. "
            "A recomendação é executar por ciclos curtos (1-2 semanas), com objetivos mensuráveis por área e revisão no fim de cada release. "
            "Regra de histórico: não apagar tarefas antigas; quando terminar uma tarefa, manter no TO DO e marcar explicitamente com `CONCLUIDO`."
        ),
    }
