from .dashboard import *
from .graficos import *
from .projetos import *
from .furos import *
from .medicoes import *
from .maquinas import *
from .empregados import *
from .registos import *
from .materiais import *
from .configuracao_perfuracao import *
from .historico_configuracao import *
from .empregado_furo import *
from .diario_tecnico import *
from .empregado_area import *
from .definicoes import *
from .analytics import *
from .opcoes import *
from .despesas import *
