from .dashboard import *
from .projetos import *
from .furos import *
from .medicoes import *
from .maquinas import *
from .empregados import *
from .equipas import *
from .registos import *
from .materiais import *
from .configuracao_perfuracao import *
from .historico_configuracao import *
from .empregado_furo import *
from .diario_tecnico import *
from .empregado_area import *
from .definicoes import *
from .analytics import *
from .opcoes import *
from .despesas import *
from .maquina_avarias import *
from .modelos_3d import *
from .institucional import *
from .gestao_empresa import *
from .clientes_contratos import *
from .planeamento_turnos import *
from .assiduidade import *
