from projetos.models import (
    ConfiguracaoPerfuracaoEmpregado,
    DevolucaoMaterial,
    Despesa,
    EmpregadoFicheiro,
    EmpregadoFuro,
    EmpregadoProjeto,
    Empregados,
    Empresa,
    EventoAnalytics,
    Furo,
    FuroVersao,
    HistoricoConfiguracaoPerfuracao,
    ImportacaoFuro3DExterna,
    Individual,
    LevantamentoMaterial,
    Maquina,
    MaquinaAvaria,
    MaquinaEventoOperacional,
    Material,
    Medicao,
    PreferenciasUser,
    Projeto,
    RegistoDiarioEmpregado,
    RegistoDiarioFotoAmostra,
)


PROJETOS_MODEL_MAP = {
    "Empresa": Empresa,
    "Projeto": Projeto,
    "Furo": Furo,
    "FuroVersao": FuroVersao,
    "Empregados": Empregados,
    "EmpregadoProjeto": EmpregadoProjeto,
    "EmpregadoFicheiro": EmpregadoFicheiro,
    "Individual": Individual,
    "EmpregadoFuro": EmpregadoFuro,
    "RegistoDiarioEmpregado": RegistoDiarioEmpregado,
    "RegistoDiarioFotoAmostra": RegistoDiarioFotoAmostra,
    "Medicao": Medicao,
    "Maquina": Maquina,
    "MaquinaAvaria": MaquinaAvaria,
    "MaquinaEventoOperacional": MaquinaEventoOperacional,
    "Material": Material,
    "LevantamentoMaterial": LevantamentoMaterial,
    "DevolucaoMaterial": DevolucaoMaterial,
    "Despesa": Despesa,
    "ConfiguracaoPerfuracaoEmpregado": ConfiguracaoPerfuracaoEmpregado,
    "HistoricoConfiguracaoPerfuracao": HistoricoConfiguracaoPerfuracao,
    "PreferenciasUser": PreferenciasUser,
    "EventoAnalytics": EventoAnalytics,
    "ImportacaoFuro3DExterna": ImportacaoFuro3DExterna,
}
