# Generated by Django 6.0.3 on 2026-04-16 14:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('nif', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('morada', models.CharField(blank=True, max_length=255)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('teste', 'Teste'), ('cancelada', 'Cancelada')], default='teste', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('individual', 'Individual')], default='empresa', max_length=20)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_empregados', models.PositiveIntegerField(default=0)),
                ('limite_projetos', models.PositiveIntegerField(default=0)),
                ('limite_furos', models.PositiveIntegerField(default=0)),
                ('limite_armazenamento_gb', models.PositiveIntegerField(default=5)),
                ('permite_multiplos_utilizadores', models.BooleanField(default=True)),
                ('acesso_dashboard_empresa', models.BooleanField(default=True)),
                ('acesso_painel_empregado', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('platform_owner', 'Platform Owner'), ('platform_admin', 'Platform Admin'), ('empresa_admin', 'Empresa Admin'), ('empresa_gestor', 'Empresa Gestor'), ('empregado', 'Empregado')], default='empregado', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_acesso', to='plataforma.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_plataforma', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='plataforma.plano'),
        ),
        migrations.CreateModel(
            name='SubscricaoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ativa', 'Ativa'), ('pendente', 'Pendente'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa')], default='pendente', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('renovacao_automatica', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscricoes', to='plataforma.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscricoes', to='plataforma.plano')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='plataforma.empresa')),
                ('subscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='plataforma.subscricaoempresa')),
            ],
        ),
    ]
