# Generated by Django 6.0.3 on 2026-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='ativa',
            new_name='ativo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='estado',
        ),
        migrations.AddField(
            model_name='empresa',
            name='limite_utilizadores',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nome_comercial',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('teste', 'Teste'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada')], default='teste', max_length=20),
        ),
    ]
