# Generated by Django 6.0.4 on 2026-04-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_alter_empresa_options_rename_ativa_empresa_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilplataforma',
            name='tipo_acesso',
            field=models.CharField(choices=[('platform_owner', 'Platform Owner'), ('platform_admin', 'Platform Admin'), ('empresa_admin', 'Empresa Admin'), ('empresa_gestor', 'Empresa Gestor'), ('empregado', 'Empregado'), ('individual', 'Individual')], default='individual', max_length=30),
        ),
    ]
