# Generated by Django 6.0.4 on 2026-04-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_plano_periodos_cobranca_disponiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='categoria',
            field=models.CharField(choices=[('subscricao', 'Subscrição'), ('renovacao', 'Renovação'), ('pagamento_inicial', 'Pagamento inicial'), ('reembolso', 'Reembolso'), ('ajuste', 'Ajuste'), ('despesa_operacional', 'Despesa operacional'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='entidade_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='metodo_pagamento',
            field=models.CharField(choices=[('manual', 'Manual'), ('transferencia', 'Transferência'), ('referencia', 'Referência'), ('debito_direto', 'Débito direto'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='natureza_fluxo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=20),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='valor_imposto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroplataforma',
            name='valor_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentofinanceiroplataforma',
            name='ciclo_cobranca',
            field=models.CharField(choices=[('1', '1 mês'), ('3', '3 meses'), ('6', '6 meses'), ('12', '12 meses'), ('mensal', 'Mensal'), ('anual', 'Anual'), ('unico', 'Único')], default='unico', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscricaoempresa',
            name='ciclo_cobranca',
            field=models.CharField(choices=[('1', '1 mês'), ('3', '3 meses'), ('6', '6 meses'), ('12', '12 meses'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=20),
        ),
    ]
