# Generated by Django 6.0.4 on 2026-04-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_movimentofinanceiroplataforma_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentofinanceiroplataforma',
            name='categoria',
            field=models.CharField(choices=[('subscricao', 'Subscrição'), ('renovacao', 'Renovação'), ('pagamento_inicial', 'Pagamento inicial'), ('reembolso', 'Reembolso'), ('ajuste', 'Ajuste'), ('despesa_operacional', 'Despesa operacional'), ('despesa_servidor', 'Servidor / alojamento'), ('despesa_publicidade_youtube', 'Publicidade YouTube'), ('despesa_publicidade_facebook', 'Publicidade Facebook'), ('despesa_publicidade_tiktok', 'Publicidade TikTok'), ('despesa_dominio', 'Domínio / endereço'), ('despesa_ssl_https', 'SSL / HTTPS'), ('despesa_marketing', 'Marketing'), ('despesa_software', 'Software / ferramentas'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AlterField(
            model_name='movimentofinanceiroplataforma',
            name='tipo_movimento',
            field=models.CharField(choices=[('cobranca', 'Cobrança'), ('pagamento', 'Pagamento'), ('ajuste', 'Ajuste'), ('reembolso', 'Reembolso'), ('despesa', 'Despesa')], default='cobranca', max_length=20),
        ),
    ]
