# Generated by Django 6.0.4 on 2026-04-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_empresa_valor_total_ganho_furo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFeatureAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_feature', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_features', to='plataforma.empresa')),
                ('perfil_plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_features', to='plataforma.perfilplataforma')),
            ],
            options={
                'ordering': ['chave_feature'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('empresa__isnull', False)), fields=('empresa', 'chave_feature'), name='unique_feature_por_empresa'), models.UniqueConstraint(condition=models.Q(('perfil_plataforma__isnull', False)), fields=('perfil_plataforma', 'chave_feature'), name='unique_feature_por_perfil')],
            },
        ),
    ]
