# Generated by Django 6.0.4 on 2026-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_configuracaofeatureacesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentofinanceiroplataforma',
            name='metodo_pagamento',
            field=models.CharField(choices=[('manual', 'Manual'), ('paypal', 'PayPal'), ('transferencia', 'Transferência'), ('referencia', 'Referência'), ('debito_direto', 'Débito direto'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='manual', max_length=20),
        ),
    ]
