# Generated by Django 6.0.4 on 2026-04-26 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_alter_movimentofinanceiroplataforma_metodo_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagamentoPlataforma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='principal', max_length=50, unique=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('paypal_password', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento da Plataforma',
                'verbose_name_plural': 'Configurações de Pagamento da Plataforma',
            },
        ),
    ]
