# Generated by Django 6.0.4 on 2026-04-29 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_configuracaopagamentoplataforma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuroArquivadoPlataforma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('furo_id_origem', models.UUIDField(db_index=True)),
                ('projeto_id_origem', models.UUIDField(blank=True, db_index=True, null=True)),
                ('nome_furo', models.CharField(blank=True, max_length=200)),
                ('estado_no_arquivo', models.CharField(default='concluido', max_length=30)),
                ('versao_arquivo', models.PositiveIntegerField(default=1)),
                ('terminado_em', models.DateTimeField(blank=True, null=True)),
                ('dados_snapshot', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furos_arquivados_plataforma', to='plataforma.empresa')),
                ('terminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furos_arquivados_terminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Furo arquivado da plataforma',
                'verbose_name_plural': 'Furos arquivados da plataforma',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('furo_id_origem', 'versao_arquivo'), name='unique_furo_arquivado_versao')],
            },
        ),
    ]
