# Generated by Django 6.0.4 on 2026-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_furoarquivadoplataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='plataforma/empresas/logos/'),
        ),
    ]
