# Generated by Django 6.0.4 on 2026-05-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0016_empresa_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='geologia_score_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
