# Generated by Django 6.0.4 on 2026-04-22 00:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0011_empresa_valor_total_ganho_furo'),
        ('projetos', '0010_importacaofuro3dexterna'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseImagemAI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=180)),
                ('tipo_documento', models.CharField(choices=[('caixa_cilindrica', 'Caixa cilíndrica com testemunho'), ('relatorio_trabalhador', 'Relatório manuscrito de trabalhador')], default='caixa_cilindrica', max_length=40)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('revisao_manual', 'Revisão manual'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('imagem_original', models.ImageField(upload_to='inspecao_ai/originais/')),
                ('imagem_processada', models.ImageField(blank=True, null=True, upload_to='inspecao_ai/processadas/')),
                ('marcador_predominante', models.CharField(choices=[('azul', 'Azul'), ('preto', 'Preto'), ('misto', 'Misto'), ('indefinido', 'Indefinido')], default='indefinido', max_length=20)),
                ('texto_detectado', models.BooleanField(default=False)),
                ('texto_extraido_bruto', models.TextField(blank=True)),
                ('texto_normalizado', models.TextField(blank=True)),
                ('confianca_media', models.FloatField(blank=True, null=True)),
                ('motor_analise', models.CharField(default='local_vision_v1', max_length=80)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('observacoes', models.TextField(blank=True)),
                ('erro_analise', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_imagem_ai_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_imagem_ai', to='plataforma.empresa')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_imagem_ai', to='projetos.furo')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_imagem_ai', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Análise de imagem AI',
                'verbose_name_plural': 'Análises de imagem AI',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DeteccaoImagemAI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('tipo_deteccao', models.CharField(choices=[('texto_marcador', 'Texto a marcador'), ('zona_interesse', 'Zona de interesse')], default='texto_marcador', max_length=30)),
                ('marcador_cor', models.CharField(choices=[('azul', 'Azul'), ('preto', 'Preto'), ('misto', 'Misto'), ('indefinido', 'Indefinido')], default='indefinido', max_length=20)),
                ('confianca', models.FloatField(blank=True, null=True)),
                ('texto_sugerido', models.CharField(blank=True, max_length=255)),
                ('caixa_delimitadora', models.JSONField(blank=True, default=dict)),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes', to='inspecao_ai.analiseimagemai')),
            ],
            options={
                'verbose_name': 'Deteção de imagem AI',
                'verbose_name_plural': 'Deteções de imagem AI',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
