# Generated by Django 6.0.4 on 2026-04-22 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao_ai', '0001_initial'),
        ('plataforma', '0011_empresa_valor_total_ganho_furo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessaoAI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Nova conversa AI', max_length=180)),
                ('ativa', models.BooleanField(default=True)),
                ('ultimo_resumo_contexto', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessoes_ai', to='plataforma.empresa')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessoes_ai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão Chat AI',
                'verbose_name_plural': 'Sessões Chat AI',
                'ordering': ['-atualizado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChatMensagemAI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('user', 'Utilizador'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=20)),
                ('conteudo', models.TextField()),
                ('metadados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='inspecao_ai.chatsessaoai')),
            ],
            options={
                'verbose_name': 'Mensagem Chat AI',
                'verbose_name_plural': 'Mensagens Chat AI',
                'ordering': ['criado_em'],
            },
        ),
    ]
