# Generated by Django 6.0.4 on 2026-04-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao_ai', '0002_chatsessaoai_chatmensagemai'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiseimagemai',
            name='campos_extraidos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
