# Generated by Django 6.0.4 on 2026-04-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecao_ai', '0006_memoriatrabalhoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoriatrabalhoai',
            name='area',
            field=models.CharField(choices=[('ocr_relatorios', 'OCR relatórios'), ('ocr_caixas', 'OCR caixas'), ('chatbox', 'Chatbox'), ('memoria_operacional', 'Memória operacional'), ('plataforma', 'Plataforma'), ('geral', 'Geral')], default='geral', max_length=40),
        ),
    ]
