# Generated by Django 6.0.4 on 2026-05-23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspecao_ai", "0007_alter_memoriatrabalhoai_area"),
        ("plataforma", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExemploTreinoAI",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("caixa_cilindrica", "Caixa cilíndrica com testemunho"),
                            ("relatorio_trabalhador", "Relatório manuscrito de trabalhador"),
                        ],
                        max_length=40,
                    ),
                ),
                ("campo_semantico", models.CharField(max_length=80)),
                ("indice_campo", models.PositiveIntegerField()),
                ("versao_rotulo", models.PositiveIntegerField(default=1)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "origem",
                    models.CharField(
                        choices=[("validacao_manual", "Validação manual")],
                        default="validacao_manual",
                        max_length=30,
                    ),
                ),
                ("entrada_modelo", models.JSONField(blank=True, default=dict)),
                ("valor_previsto", models.TextField(blank=True)),
                ("rotulo_validado", models.TextField()),
                ("acertou_previsao", models.BooleanField(blank=True, null=True)),
                ("motor_analise", models.CharField(blank=True, max_length=80)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemplos_treino",
                        to="inspecao_ai.analiseimagemai",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemplos_treino_ai",
                        to="plataforma.empresa",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exemplos_treino_ai_validados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exemplo de treino AI",
                "verbose_name_plural": "Exemplos de treino AI",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="exemplotreinoai",
            constraint=models.UniqueConstraint(
                fields=("analise", "indice_campo", "versao_rotulo"),
                name="unique_exemplo_treino_ai_analise_campo_versao",
            ),
        ),
        migrations.AddIndex(
            model_name="exemplotreinoai",
            index=models.Index(fields=["empresa", "tipo_documento", "ativo"], name="idx_treino_ai_empresa_tipo"),
        ),
    ]
