# Generated by Django 6.0.4 on 2026-04-19 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0003_alter_perfilplataforma_tipo_acesso'),
        ('projetos', '0002_rename_data_fim_projeto_data_fim_proj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('magcruiser', 'MagCruiser')], max_length=40)),
                ('canal', models.CharField(choices=[('usb_serial', 'USB / Serial'), ('bluetooth', 'Bluetooth'), ('arquivo', 'Arquivo'), ('simulador', 'Simulador')], max_length=40)),
                ('identificador_fisico', models.CharField(blank=True, max_length=120)),
                ('porta', models.CharField(blank=True, max_length=120)),
                ('mac_address', models.CharField(blank=True, max_length=120)),
                ('baudrate', models.IntegerField(default=115200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LeituraDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_device', models.DateTimeField()),
                ('profundidade_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inclinacao_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('azimute_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payload_bruto', models.JSONField(blank=True, default=dict)),
                ('payload_texto', models.TextField(blank=True)),
                ('qualidade', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_dispositivos', to='plataforma.empresa')),
            ],
            options={
                'verbose_name': 'Leitura de Dispositivo',
                'verbose_name_plural': 'Leituras de Dispositivos',
                'ordering': ['-timestamp_device', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LeituraDispositivoMedicaoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_medicao', to='dispositivos.leituradispositivo')),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_dispositivo', to='projetos.medicao')),
            ],
            options={
                'verbose_name': 'Ligação Leitura-Medição',
                'verbose_name_plural': 'Ligações Leitura-Medição',
            },
        ),
        migrations.CreateModel(
            name='SessaoDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('ligando', 'Ligando'), ('ligado', 'Ligado'), ('erro', 'Erro'), ('encerrada', 'Encerrada')], default='criada', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('terminado_em', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='dispositivos.dispositivo')),
                ('empregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_dispositivos', to='projetos.empregados')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_dispositivos', to='plataforma.empresa')),
                ('furo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_dispositivo', to='projetos.furo')),
            ],
            options={
                'verbose_name': 'Sessão de Dispositivo',
                'verbose_name_plural': 'Sessões de Dispositivos',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.AddField(
            model_name='leituradispositivo',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='dispositivos.sessaodispositivo'),
        ),
        migrations.CreateModel(
            name='SurveyShot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inclinacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('azimute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('magnetismo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valido', models.BooleanField(default=True)),
                ('origem', models.CharField(choices=[('magcruiser', 'MagCruiser'), ('manual', 'Manual'), ('importacao', 'Importação'), ('simulador', 'Simulador')], default='magcruiser', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_shots', to='plataforma.empresa')),
                ('furo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_shots', to='projetos.furo')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='dispositivos.sessaodispositivo')),
            ],
            options={
                'verbose_name': 'Survey Shot',
                'verbose_name_plural': 'Survey Shots',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LeituraBrutaDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequencia', models.PositiveIntegerField(default=1)),
                ('payload_texto', models.TextField(blank=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('payload_hex', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_brutas_dispositivos', to='plataforma.empresa')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_brutas', to='dispositivos.sessaodispositivo')),
            ],
            options={
                'verbose_name': 'Leitura Bruta de Dispositivo',
                'verbose_name_plural': 'Leituras Brutas de Dispositivos',
                'ordering': ['-recebido_em'],
                'unique_together': {('sessao', 'sequencia')},
            },
        ),
    ]
