# Generated by Django 6.0.4 on 2026-04-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('plataforma', '0003_alter_perfilplataforma_tipo_acesso'),
        ('projetos', '0002_rename_data_fim_projeto_data_fim_proj_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='surveyshot',
            index=models.Index(fields=['empresa', 'furo'], name='dispositivo_empresa_d20fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyshot',
            index=models.Index(fields=['sessao', 'criado_em'], name='dispositivo_sessao__f1fc15_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyshot',
            index=models.Index(fields=['furo', 'profundidade'], name='dispositivo_furo_id_b008a2_idx'),
        ),
    ]
