# Generated by Django 6.0.4 on 2026-04-20 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_surveyshot_dispositivo_empresa_d20fa8_idx_and_more'),
        ('plataforma', '0003_alter_perfilplataforma_tipo_acesso'),
        ('projetos', '0002_rename_data_fim_projeto_data_fim_proj_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leiturabrutadispositivo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='leiturabrutadispositivo',
            name='metadados',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leiturabrutadispositivo',
            name='origem',
            field=models.CharField(choices=[('usb', 'USB'), ('bluetooth', 'Bluetooth'), ('manual', 'Manual'), ('importacao', 'Importação'), ('simulador', 'Simulador')], default='usb', max_length=30),
        ),
        migrations.AddField(
            model_name='leiturabrutadispositivo',
            name='payload_binario',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leituradispositivo',
            name='leitura_bruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras_processadas', to='dispositivos.leiturabrutadispositivo'),
        ),
        migrations.AlterField(
            model_name='leituradispositivo',
            name='timestamp_device',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['empresa', 'ativo'], name='dispositivo_empresa_5334aa_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['empresa', 'tipo'], name='dispositivo_empresa_4e02cf_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['empresa', 'canal'], name='dispositivo_empresa_3730ab_idx'),
        ),
        migrations.AddIndex(
            model_name='leiturabrutadispositivo',
            index=models.Index(fields=['empresa', 'recebido_em'], name='dispositivo_empresa_91170a_idx'),
        ),
        migrations.AddIndex(
            model_name='leiturabrutadispositivo',
            index=models.Index(fields=['sessao', 'sequencia'], name='dispositivo_sessao__0f285b_idx'),
        ),
        migrations.AddIndex(
            model_name='leituradispositivo',
            index=models.Index(fields=['empresa', 'criado_em'], name='dispositivo_empresa_a28ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='leituradispositivo',
            index=models.Index(fields=['sessao', 'criado_em'], name='dispositivo_sessao__dcd60a_idx'),
        ),
        migrations.AddIndex(
            model_name='leituradispositivo',
            index=models.Index(fields=['sessao', 'timestamp_device'], name='dispositivo_sessao__df8e48_idx'),
        ),
        migrations.AddIndex(
            model_name='leituradispositivo',
            index=models.Index(fields=['sessao', 'profundidade_m'], name='dispositivo_sessao__1069c6_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaodispositivo',
            index=models.Index(fields=['empresa', 'status'], name='dispositivo_empresa_7cc179_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaodispositivo',
            index=models.Index(fields=['dispositivo', 'iniciado_em'], name='dispositivo_disposi_af43ac_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaodispositivo',
            index=models.Index(fields=['furo', 'iniciado_em'], name='dispositivo_furo_id_ae7f78_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaodispositivo',
            index=models.Index(fields=['empregado', 'iniciado_em'], name='dispositivo_emprega_ed150e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('porta', ''), _negated=True), fields=('empresa', 'porta'), name='unique_dispositivo_empresa_porta'),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('mac_address', ''), _negated=True), fields=('empresa', 'mac_address'), name='unique_dispositivo_empresa_mac_address'),
        ),
        migrations.AddConstraint(
            model_name='leiturabrutadispositivo',
            constraint=models.UniqueConstraint(fields=('sessao', 'sequencia'), name='unique_leitura_bruta_sessao_sequencia'),
        ),
    ]
