# Generated by Django 6.0.4 on 2026-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_alter_leiturabrutadispositivo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leiturabrutadispositivo',
            name='origem',
            field=models.CharField(default='usb', max_length=30),
        ),
    ]
