# Generated by Django 6.0.4 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispositivos", "0004_alter_leiturabrutadispositivo_origem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leiturabrutadispositivo",
            name="origem",
            field=models.CharField(
                choices=[
                    ("usb", "USB"),
                    ("bluetooth", "Bluetooth"),
                    ("manual", "Manual"),
                    ("importacao", "Importação"),
                    ("simulador", "Simulador"),
                ],
                default="usb",
                max_length=30,
            ),
        ),
    ]
