# Generated by Django 6.0.4 on 2026-04-29 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_alter_leiturabrutadispositivo_origem'),
        ('plataforma', '0015_furoarquivadoplataforma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoDispositivoHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_ficheiro', models.CharField(max_length=255)),
                ('formato', models.CharField(blank=True, max_length=20)),
                ('modo_aplicacao', models.CharField(choices=[('all_existing', 'Todas (furos existentes)'), ('latest_existing', 'Última por furo (furos existentes)'), ('all_create_missing', 'Todas + criar furos em falta')], default='all_existing', max_length=30)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('total_gravadas', models.PositiveIntegerField(default=0)),
                ('total_ignoradas', models.PositiveIntegerField(default=0)),
                ('furos_criados', models.PositiveIntegerField(default=0)),
                ('furos_sem_match', models.JSONField(blank=True, default=list)),
                ('resumo_por_furo', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_importacoes_dispositivo', to='plataforma.empresa')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_importacoes', to='dispositivos.sessaodispositivo')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_importacoes_dispositivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Importação de Dispositivo',
                'verbose_name_plural': 'Históricos de Importação de Dispositivo',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='dispositivo_empresa_d284ae_idx'), models.Index(fields=['sessao', 'criado_em'], name='dispositivo_sessao__69792e_idx')],
            },
        ),
    ]
